version: 2.1
orbs:
  node: circleci/node@5.1.0
  cypress: cypress-io/cypress@2.2.0
  dotenv: anilanar/dotenv@1.0.0
  ms-teams: opub/ms-teams-orb@1.0.3

parameters:
  image-tag:
    type: string
    default: '20.11.0'

  env:
    type: enum
    description: 'The environment name to deploy tag or branch'
    enum: ['', 'integration', 'staging', 'production']
    default: ''

  version:
    type: string
    description: 'The version to be deployed on environment. Can be a tag or branch name'
    default: ${CIRCLE_BRANCH}

  workflow:
    type: enum
    description: 'Trigger a specific workflow'
    enum: ['build', 'deploy', 'rebase', 'rebase-all']
    default: 'build'

executors:
  job-executor:
    docker:
      - image: cimg/node:<< pipeline.parameters.image-tag >>
    resource_class: small
  app-executor:
    docker:
      - image: cimg/node:<< pipeline.parameters.image-tag >>
    resource_class: medium+
  server-executor:
    docker:
      - image: cimg/node:<< pipeline.parameters.image-tag >>
    resource_class: large
  cypress-executor:
    docker:
      - image: 'cypress/browsers:node-20.11.0-chrome-121.0.6167.184-1-ff-123.0-edge-121.0.2277.128-1'
    resource_class: large
commands:
  switch-branch:
    description: 'Switch to branch or tags'
    steps:
      - when:
          condition:
            and:
              - not:
                  equal: [<< pipeline.git.branch >>, << pipeline.parameters.version >>]
          steps:
            - run:
                name: 'Checkout'
                command: |
                  CURRENT_VERSION="<< pipeline.parameters.version >>"
                  if [[ "$CURRENT_VERSION" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)?$ ]]; then
                    echo "Checking out tag $CUSTOM_BRANCH"
                    git fetch --force --tags origin
                    git checkout  tags/<< pipeline.parameters.version >> -b << pipeline.parameters.version >>-branch
                  else
                    echo "Checking out branch $CUSTOM_BRANCH"
                    git checkout --force -B << pipeline.parameters.version >> --track origin/<< pipeline.parameters.version >>
                  fi

  configure-executor:
    description: 'Configuration docker'
    steps:
      - setup_remote_docker
  configure-git:
    steps:
      - run:
          name: 'Set git configuration'
          command: |
            git config --global user.name "$GIT_USER_NAME"
            git config --global user.email "$GIT_USER_EMAIL"
            git remote remove origin
            git remote add origin https://${GH_TOKEN}@github.com/ClubMediterranee/cm-payment.git

  release-tag:
    parameters:
      env:
        type: enum
        description: 'The environment name to deploy tag or branch'
        enum: ['', 'integration', 'staging', 'production']
        default: 'integration'
    steps:
      - dotenv/source:
          path: .circleci/.env.<< parameters.env >>
      - workspace-restore
      - install
      - run: SKIP_DEPLOY=true yarn dlx -p @cmflow/cli cmrelease

  deploy-env:
    parameters:
      env:
        type: enum
        description: 'The environment name to deploy tag or branch'
        enum: ['', 'integration', 'staging', 'production']
        default: 'integration'
      version:
        type: string
        description: 'The version to be deployed on environment'
    steps:
      - dotenv/source:
          path: .circleci/.env.<< parameters.env >>
      - heroku-deploy:
          app: $HEROKU_APP
      - ms-teams/report:
          webhook_url: $TEAMS_WEBHOOK
          only_on_fail: false
          message: 'Deployment of version << parameters.version >> on << parameters.env >> environment is __build_status__.'

  install:
    description: 'Yarn install with cache optimization'
    steps:
      - node/install-packages:
          check-cache: never
          pkg-manager: yarn-berry
          with-cache: false

  heroku-deploy:
    parameters:
      process-type:
        type: string
        description: 'The heroku process type'
        default: 'web'
      app:
        type: string
        description: 'The heroku app name'
    steps:
      - run:
          name: 'Heroku login'
          command: npx heroku@7.67.2 container:login
      - run:
          name: 'Docker login & build'
          command: |
            docker login --username=_ --password=${HEROKU_API_KEY} registry.heroku.com
            docker build . -t registry.heroku.com/<< parameters.app >>/<< parameters.process-type >>
      - run:
          name: 'Docker push'
          command: docker push registry.heroku.com/<< parameters.app >>/<< parameters.process-type >>
      - run:
          name: 'Heroku deploy'
          command: npx heroku@7.67.2 container:release web --app << parameters.app >>

  workspace-restore:
    description: 'Restore workspace'
    steps:
      - attach_workspace:
          at: .

  test-update-coverage:
    description: 'Update coverage file'
    parameters:
      package:
        type: string
        description: 'package path under packages directory'
    steps:
      - run: yarn tsc:build
      - run:
          name: Unit test
          command: yarn test:ci --projects=@clubmed/<< parameters.package >> --reporter=default --reporter=junit
      - persist_to_workspace:
          root: .
          paths:
            - ./packages/<< parameters.package >>/vitest.config.mts
      - store_test_results:
          path: ./packages/<< parameters.package >>/reports/vitest
      - store_artifacts:
          path: ./packages/<< parameters.package >>/coverage
jobs:
  #######################################################################
  # JOB: INSTALL
  #######################################################################
  lint:
    executor: app-executor
    steps:
      - configure-executor
      - checkout
      - install
      - run:
          name: Lint
          command: yarn lint:ci
      - store_test_results:
          path: reports
      - store_artifacts:
          path: ./reports
  test-app:
    executor: app-executor
    steps:
      - configure-executor
      - checkout
      - install
      - test-update-coverage:
          package: app

  test-app-cy:
    executor: cypress-executor
    parallelism: 6
    steps:
      - configure-executor
      - checkout
      - install
      - run:
          name: Cypress test
          command: yarn cy:test:ci
      - store_test_results:
          path: packages/app/reports/cypress
      - store_artifacts:
          path: ./packages/app/reports/cypress/screenshots

  build:
    executor: app-executor
    steps:
      - configure-executor
      - checkout
      - install
      - run:
          name: Build
          command: yarn build:spec && yarn build

  release:
    executor: app-executor
    parameters:
      version:
        type: string
        description: 'The version to be deployed on environment'
      env:
        type: enum
        description: 'The environment name to deploy tag or branch'
        enum: ['', 'integration', 'staging', 'production']
        default: 'integration'
    steps:
      - run:
          name: 'Log parameters'
          command: |
            echo "Env: << parameters.env >>"
            echo "Version/Branch: << parameters.version >>"
      - configure-executor
      - checkout
      - switch-branch
      #      - run:
      #          name: Write job data
      #          command: echo "<< parameters.version >>" > packages/server/resources/release.info
      - release-tag:
          env: << parameters.env >>

  deploy:
    executor: app-executor
    parameters:
      version:
        type: string
        description: 'The version to be deployed on environment'
      env:
        type: enum
        description: 'The environment name to deploy tag or branch'
        enum: ['', 'integration', 'staging', 'production']
        default: 'integration'
    steps:
      - run:
          name: 'Log parameters'
          command: |
            echo "Env: << parameters.env >>"
            echo "Version/Branch: << parameters.version >>"
      - configure-executor
      - checkout
      - switch-branch
      #      - run:
      #          name: Write job data
      #          command: echo "<< parameters.version >>" > packages/server/resources/release.info
      - deploy-env:
          env: << parameters.env >>
          version: << parameters.version >>

  rebase-all:
    executor: job-executor
    environment:
      PRODUCTION_BRANCH: main
    steps:
      - checkout
      - configure-git
      - run:
          name: 'Republish branches'
          command: yarn dlx -p @cmflow/cli cm republish
  rebase:
    executor: job-executor
    environment:
      PRODUCTION_BRANCH: main
    steps:
      - checkout
      - configure-git
      - run:
          name: 'Republish branch'
          command: yarn dlx -p @cmflow/cli cm push

workflows:
  # rebase all branches
  rebase-all:
    when:
      equal: ['rebase-all', << pipeline.parameters.workflow >>]
    jobs:
      - rebase-all:
          context: api

  # rebase all branches
  rebase:
    when:
      equal: ['rebase', << pipeline.parameters.workflow >>]
    jobs:
      - rebase:
          filters:
            branches:
              ignore: main
          context: api

  # deploy a branch or tag
  deploy-with-parameters:
    when:
      or:
        - not:
            equal: ['', << pipeline.parameters.env >>]
        - equal: ['deploy', << pipeline.parameters.workflow >>]
    jobs:
      - deploy:
          env: << pipeline.parameters.env >>
          version: << pipeline.parameters.version >>
          context: api
  # default workflow when a commit is pushed on repository.
  build-and-release:
    when:
      equal: ['build', << pipeline.parameters.workflow >>]
    jobs:
      - lint
      - test-app
      - test-app-cy
      - build
      - release:
          env: staging
          version: << pipeline.parameters.version >>
          requires:
            - lint
            - test-app
            - test-app-cy
            - build
          filters:
            branches:
              only: main
          context: api
      - deploy:
          env: staging
          version: main
          requires:
            - release
          filters:
            branches:
              only: main
          context: api
      - storybook:
          requires:
            - lint
            - test-app
            - test-app-cy
            - build
          filters:
            branches:
              only: main
          context: api
