###############################################################################
###############################################################################
##               ____ _       _       __  __          _                      ##
##              / ___| |_   _| |__   |  \/  | ___  __| |                     ##
##             | |   | | | | | '_ \  | |\/| |/ _ \/ _` |                     ##
##             | |___| | |_| | |_) | | |  | |  __/ (_| |_                    ##
##              \____|_|\__,_|_.__/  |_|  |_|\___|\__,_(_)                   ##
##                                                                           ##
## description     : CI/CD configuration                                     ##
## author          : DevOps team <DevOps@clubmedoffice.onmicrosoft.com>      ##
## sources         : <https://scm.clubmed.com/clubmed/ui/trident-ui>         ##
##                                                                           ##
###############################################################################
###############################################################################
---
include:
  - project: 'clubmed/templates'
    ref: 'master'
    file: 'CI/library/commons.yaml'
  - project: 'clubmed/templates'
    ref: 'master'
    file: 'CI/library/docker.yaml'
  - project: 'clubmed/templates'
    ref: 'master'
    file: 'CI/library/docker-aws.yaml'
  - project: 'clubmed/templates'
    ref: 'master'
    file: 'CI/git-flow.yaml'
  - project: 'clubmed/templates'
    ref: 'master'
    file: 'CI/library/gitlab-api-utils.yaml'
  - local: '.gitlab/ci/commons.yml'
  - local: '.gitlab/ci/ci-lint.yml'
  - local: '.gitlab/ci/dev-branches.yml'
  - local: '.gitlab/ci/release.yml'
  - local: '.gitlab/ci/tags.yml'
  - local: '.gitlab/ci/proxy.yml'
  - local: '.gitlab/ci/node.yml'

variables:
  ENV_DEV_LIFETIME: '1 week'
  DOCKER_IMAGE: 'payment-sdk'
  BASH_ENV: 'gitlab-pipeline.env'
  GIT_CLEAN_FLAGS: '-ffdx -e $BASH_ENV'
  NODE_VERSION: 22.17.1
  NODE_IMG: 'node:22.17.0-bullseye'
  SEMANTIC_RELEASE_OPTS: ''
  BASE_DN: 'sdk-payment.pro.clubmed'
  AWS_STACK: 'sdk-payment'
  DEPRECATION_MESSAGE: 'package deprecated from a manual action in CI - this version may be problematic'

workflow:
  rules:
    # trigger for any tag
    - if: '$CI_COMMIT_TAG'
      when: always
    # never trigger for releases creation
    - if: '$CI_COMMIT_REF_NAME == "develop" && $CI_COMMIT_MESSAGE =~ /^chore\(release\).*/'
      when: never
    # trigger when a merge-request is opened but do not trigger the default branch pipeline to avoid duplicate
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    # final fallback: trigger for all commits & tags
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "web"'

stages:
  - test_ci
  - test
  - storybook:dev
  - version:bump
  - version:storybook
  - version:publish
  - version:lifecycle
  - release:make
  - release:publish

cache:
  - key:
      files:
        - package-lock.json
    paths:
      - node_modules/
      - .npm/
      - .pnpm/
    policy: pull
    untracked: true

lint:
  extends: .node_install_dependencies
  stage: test
  variables:
    ESLINT_CODE_QUALITY_REPORT: gl-codequality.json
  script:
    - pnpm run lint --quiet --format eslint-formatter-gitlab
  artifacts:
    when: always
    reports:
      codequality: gl-codequality.json
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_COMMIT_REF_NAME == "develop" && $CI_COMMIT_MESSAGE =~ /^chore\(release\).*/'
      when: never
    - when: always
build:
    extends: .node_install_dependencies
    stage: test
    script:
        - pnpm run build
    artifacts:
        when: always
        paths:
        - packages/sdk/dist/
        - packages/sandbox/dist/
        expire_in: 1 week
    rules:
      - if: '$CI_COMMIT_TAG'
        when: always
      - if: '$CI_COMMIT_REF_NAME == "develop" && $CI_COMMIT_MESSAGE =~ /^chore\(release\).*/'
        when: never
      - when: always
test:
  extends: .node_install_dependencies
  stage: test
  variables:
    NODE_IMG: 'mcr.microsoft.com/playwright:v1.54.2'
  script:
    - npx playwright install --with-deps
    - pnpm run test
  artifacts:
    when: always
    reports:
      junit: ./reports/vitest/test-results.xml
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_COMMIT_REF_NAME == "develop" && $CI_COMMIT_MESSAGE =~ /^chore\(release\).*/'
      when: never
    - when: always
