branches:
  - '+([0-9])?(.{+([0-9]),x}).x'
  - 'master'
  - name: 'next-release'
    prerelease: 'rc'
  - name: 'develop'
    prerelease: 'beta'

plugins:
  - path: '@semantic-release/commit-analyzer'
  - path: '@semantic-release/npm'
    npmPublish: false
  - path: '@semantic-release/release-notes-generator'
    commit: '-/commit'
  - path: '@semantic-release/changelog'
    changelogFile: 'CHANGELOG.md'
    changelogTitle: '# ClubMed Payment SDK changelog'
  - path: '@semantic-release/exec'
    verifyReleaseCmd: 'echo "${nextRelease.version}" > /tmp/next_release_version'
  - path: '@semantic-release/git'
    assets:
      - 'CHANGELOG.md'
      - 'package.json',
      - './packages/sdk/package.json',
      - './packages/sandbox/package.json',
      - 'pnpm-lock.yaml'
      - 'vitest.config.ts'
    message: |
      chore(release): ${nextRelease.version}

      ${nextRelease.notes}
  - path: '@saithodev/semantic-release-backmerge'
    clearWorkspace: true
    restoreWorkspace: true
    backmergeBranches:
      - from: 'master'
        to: 'develop'
