services:
  payment-apps:
    build:
      args:
        - NODE_ENV=${NODE_ENV:-development}
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: cm-payment-apps
    restart: unless-stopped

    environment:
      - PORT=8080
      - CLUBMED_API_URL=${CLUBMED_API_URL:-https://api.integ.clubmed.com}
      - API_KEY=${API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment-apps.rule=Host(`localhost`)"
      - "traefik.http.services.payment-apps.loadbalancer.server.port=8080"
      - "app.description=Club Med Payment Applications"
      - "app.app.path=/"
      - "app.starter.path=/starter"
      - "app.storybook.path=/storybook"
      - "app.docs.path=/docs"

networks:
  default:
    driver: bridge
