packages:
  - packages/*

allowBuilds:
  "@scarf/scarf": false
  "@swc/core": false
  core-js: false
  core-js-pure: false
  esbuild: false
  msw: false

minimumReleaseAgeExclude:
  - vite@8.1.0

onlyBuiltDependencies:
  - "@scarf/scarf"
  - "@swc/core"
  - core-js
  - core-js-pure
  - esbuild
  - msw

patchedDependencies:
  directus-sdk-typegen@0.2.1: patches/directus-sdk-typegen@0.2.1.patch
