packages:
  - packages/*

overrides:
  "@tsed/hooks": 8.31.2
  "@fastify/cookie": 11.0.2
  "@fastify/static": 9.1.3
  content-disposition: 2.0.1

allowBuilds:
  "@scarf/scarf": false
  "@swc/core": false
  core-js: false
  core-js-pure: false
  esbuild: false
  msw: false

minimumReleaseAgeExclude:
  - vite@8.1.0

onlyBuiltDependencies:
  - "@scarf/scarf"
  - "@swc/core"
  - core-js
  - core-js-pure
  - esbuild
  - msw

patchedDependencies:
  directus-sdk-typegen@0.2.1: patches/directus-sdk-typegen@0.2.1.patch
