/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ClubMed API
 * Club Med, renowned for its luxury resort experiences, proudly introduces its dedicated API. This tool offers developers a gateway to the diverse services and information provided by Club Med, from vacation bookings to on-site activity details. By using this interface, partners and developers can effortlessly integrate Club Med's offerings into their platforms. Whether you're looking for destination details, making reservations, or discovering the latest promotions, the Club Med API ensures a streamlined user experience. Step into this digital realm and amplify your platforms with the Club Med API.
 * OpenAPI spec version: 0.3454.0
 */
import { fetcher } from '../utils/fetcher';
export interface LinkModel {
  /** Name of the relationship */
  rel?: string;
  /** Indicates if the link is deprecated due to unnormalized rel */
  deprecated_rel?: boolean;
  /** Indicates if it is an external link */
  external?: boolean;
  /** HTTP method to use */
  method?: string;
  /** Link to the resource */
  href?: string;
  /** A label for the link */
  label?: string;
}

/**
 * Links
 */
export type LinksModel = LinkModel[];

export interface BadRequestErrorModel {
  error_code?: string;
  concerned_key?: string;
  error_description?: string;
}

export type Errors = BadRequestErrorModel[];

export interface BadRequestModel {
  status_code?: number;
  error?: string;
  error_description?: string;
  errors?: Errors;
}

export interface UnauthorizedModel {
  status_code?: number;
  error?: string;
  error_description?: string;
}

export interface NotFoundModel {
  status_code?: number;
  error?: string;
  error_description?: string;
}

export interface ForbiddenModel {
  status_code?: number;
  error?: string;
  error_description?: string;
}

/**
 * type of product
 */
export type ProductTypeModel = (typeof ProductTypeModel)[keyof typeof ProductTypeModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductTypeModel = {
  CRUISE: 'CRUISE',
  TOUR: 'TOUR',
  JOYVIEW: 'JOYVIEW',
  VILLAGE: 'VILLAGE',
  VILLA: 'VILLA',
  SUMMER_CAMP: 'SUMMER_CAMP',
  URBAN_OASIS: 'URBAN_OASIS',
  LODGE: 'LODGE',
} as const;

export interface DiscountModelV3 {
  /** id of the applied discount on the booking */
  id: string;
}

export type DiscountsModelV3 = DiscountModelV3[];

export type ProductAreaComfortV1AnyOf = {
  /** comfort grade level */
  level?: number;
  /** comfort grade level label */
  label?: string;
};

export type ProductAreaComfortV1 = ProductAreaComfortV1AnyOf | null;

export interface ProductAreaModelV2 {
  /** id of the area */
  id: string;
  /** label of the area */
  label: string;
  comfort?: ProductAreaComfortV1;
}

export type ProductAreasModelV1 = ProductAreaModelV2[];

export type ProductLightProductAvailableServicesModel =
  (typeof ProductLightProductAvailableServicesModel)[keyof typeof ProductLightProductAvailableServicesModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductLightProductAvailableServicesModel = {
  WINTER_SPORTS: 'WINTER_SPORTS',
  SPA: 'SPA',
  PLANNING: 'PLANNING',
  ROOM_INTERVENTION: 'ROOM_INTERVENTION',
  ROOM_SERVICE: 'ROOM_SERVICE',
  WINE_BOOKING: 'WINE_BOOKING',
  MY_EXPENSE: 'MY_EXPENSE',
  ROOM_READY: 'ROOM_READY',
  DRESSCODE: 'DRESSCODE',
  SKI_EQUIPMENT: 'SKI_EQUIPMENT',
} as const;

/**
 * Indicate availabilities of global resort services
 */
export type AvailableServices = ProductLightProductAvailableServicesModel[];

export type ProductCategoryModelV1AnyOf = {
  /** product category id */
  id?: string;
  /** name of the product category. The category give the segmentation beetween our product (ex: Sun, Snow, Montain in the summer...) */
  label?: string;
};

export type ProductCategoryModelV1 = ProductCategoryModelV1AnyOf | null;

export type ProductComfortModelV1AnyOf = {
  /** comfort grade level */
  level?: number;
  /** comfort grade level label */
  label?: string;
};

export type ProductComfortModelV1 = ProductComfortModelV1AnyOf | null;

/**
 * departure date
 */
export type DepartureDetailsModelAnyOfDate = string | null;

export type DepartureDetailsModelAnyOf = {
  /** departure country label */
  country?: string;
  /** departure city label */
  city?: string;
  /** departure date */
  date?: DepartureDetailsModelAnyOfDate;
};

export type DepartureDetailsModel = DepartureDetailsModelAnyOf | null;

export type SurroundingsImages = string[];

export interface CountryModelV1 {
  /** ISO 2 country code */
  id: string;
  /** country label */
  label: string;
  /** country description */
  description?: string;
}

export type CountriesModelV1 = CountryModelV1[];

/**
 * information regarding a tour or cruise arrival
 */
export type DurationModelAnyOf = {
  /** duration in nights */
  in_nights: number;
  /** duration in days */
  in_days: number;
};

/**
 * information regarding a tour or cruise arrival
 */
export type DurationModel = DurationModelAnyOf | null;

/**
 * commercial status indicating if the product is OPEN, CLOSED or NOT_YET_OPEN
 */
export type OpeningStatus = (typeof OpeningStatus)[keyof typeof OpeningStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OpeningStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  NOT_YET_OPEN: 'NOT_YET_OPEN',
} as const;

export interface ProductTypeDetails {
  id?: ProductTypeModel;
  /** Product type label */
  label: string;
}

/**
 * prices for all the stay without any discounts, according to terms and conditions
 */
export type InitialPriceModelV1AnyOfPerTrip = number | null;

/**
 * prices for all the stay with fees without any discounts, according to terms and conditions
 */
export type InitialPriceModelV1AnyOfPerTripWithFees = number | null;

/**
 * prices by night without any discounts, according to terms and conditions
 */
export type InitialPriceModelV1AnyOfPerNight = number | null;

/**
 * prices by night with fees without any discounts, according to terms and conditions
 */
export type InitialPriceModelV1AnyOfPerNightWithFees = number | null;

/**
 * Initial prices for the given conditions, without any discount.
 */
export type InitialPriceModelV1AnyOf = {
  /** prices for all the stay without any discounts, according to terms and conditions */
  per_trip?: InitialPriceModelV1AnyOfPerTrip;
  /** prices for all the stay with fees without any discounts, according to terms and conditions */
  per_trip_with_fees?: InitialPriceModelV1AnyOfPerTripWithFees;
  /** prices by night without any discounts, according to terms and conditions */
  per_night?: InitialPriceModelV1AnyOfPerNight;
  /** prices by night with fees without any discounts, according to terms and conditions */
  per_night_with_fees?: InitialPriceModelV1AnyOfPerNightWithFees;
};

/**
 * Initial prices for the given conditions, without any discount.
 */
export type InitialPriceModelV1 = InitialPriceModelV1AnyOf | null;

/**
 * minimum price for all the stay for this product, according to terms and conditions
 */
export type BestPriceModelV1AnyOfPerTrip = number | null;

/**
 * minimum price for all the stay with fees for this product, according to terms and conditions
 */
export type BestPriceModelV1AnyOfPerTripWithFees = number | null;

/**
 * minimum price by night for this product, according to terms and conditions
 */
export type BestPriceModelV1AnyOfPerNight = number | null;

/**
 * minimum price by night with fees for this product, according to terms and conditions
 */
export type BestPriceModelV1AnyOfPerNightWithFees = number | null;

/**
 * Best prices for the given conditions.
 */
export type BestPriceModelV1AnyOf = {
  /** minimum price for all the stay for this product, according to terms and conditions */
  per_trip?: BestPriceModelV1AnyOfPerTrip;
  /** minimum price for all the stay with fees for this product, according to terms and conditions */
  per_trip_with_fees?: BestPriceModelV1AnyOfPerTripWithFees;
  /** minimum price by night for this product, according to terms and conditions */
  per_night?: BestPriceModelV1AnyOfPerNight;
  /** minimum price by night with fees for this product, according to terms and conditions */
  per_night_with_fees?: BestPriceModelV1AnyOfPerNightWithFees;
};

/**
 * Best prices for the given conditions.
 */
export type BestPriceModelV1 = BestPriceModelV1AnyOf | null;

/**
 * fee amounts for the total stay
 */
export type ProductFeeModelAnyOfPerTrip = number | null;

/**
 * fee amounts by night
 */
export type ProductFeeModelAnyOfPerNight = number | null;

export type ProductFeeModelAnyOf = {
  /** fee amounts for the total stay */
  per_trip?: ProductFeeModelAnyOfPerTrip;
  /** fee amounts by night */
  per_night?: ProductFeeModelAnyOfPerNight;
};

export type ProductFeeModel = ProductFeeModelAnyOf | null;

/**
 * type of price. (ADULT, or ROOM)
 */
export type PricePer = (typeof PricePer)[keyof typeof PricePer];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PricePer = {
  ADULT: 'ADULT',
  ROOM: 'ROOM',
} as const;

export type TermsAndConditionAccommodationModelV1AnyOf = {
  /** accommodation included for the price id */
  id?: string;
  /** accommodation included for the price label */
  label?: string;
};

export type TermsAndConditionAccommodationModelV1 =
  TermsAndConditionAccommodationModelV1AnyOf | null;

export type DepartureCityV1AnyOf = {
  /** departure city id, if any transportation */
  id?: string;
  /** departure city label, if any transportation */
  label?: string;
};

export type DepartureCityV1 = DepartureCityV1AnyOf | null;

export type DepartureLocationModelV1AnyOf = {
  /** international code if relevant (airport, train station, harbour...) */
  id?: string;
  /** label of the departure location (ex: label of the departure airport) */
  label?: string;
};

export type DepartureLocationModelV1 = DepartureLocationModelV1AnyOf | null;

/**
 * Indicates the default price display. Either per trip, either per night
 */
export type DefaultPriceDisplay = (typeof DefaultPriceDisplay)[keyof typeof DefaultPriceDisplay];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DefaultPriceDisplay = {
  per_trip: 'per_trip',
  per_night: 'per_night',
} as const;

export interface ProductTermsAndConditionsOfferModel {
  id?: string;
  label?: string;
}

export type ProductTermesAndConditionsOffersModel = ProductTermsAndConditionsOfferModel[];

/**
 * date of the journey beginning. If relevant, date of the transportation departure
 */
export type TermsAndConditionsModelV1DepartureDate = string | null;

/**
 * date of the journey ending. If any transportation, date of arrival
 */
export type TermsAndConditionsModelV1ArrivalDate = string | null;

/**
 * number of adults used to calculate the price
 */
export type TermsAndConditionsModelV1NumberOfAdults = number | null;

/**
 * Indicates the instalment count: that means on how many instalments the best price can be devided
 */
export type TermsAndConditionsModelV1InstalmentCount = number | null;

export interface TermsAndConditionsModelV1 {
  price_per?: PricePer;
  /** package in which the price is applied */
  package?: string;
  /** date of the journey beginning. If relevant, date of the transportation departure */
  departure_date?: TermsAndConditionsModelV1DepartureDate;
  /** date of the journey ending. If any transportation, date of arrival */
  arrival_date?: TermsAndConditionsModelV1ArrivalDate;
  /** duration of the stay in days, without transportation */
  stay_duration?: number;
  /** trip duration in days, including transportation if any */
  total_duration?: number;
  /** refreshed every 24 hours */
  number_of_rooms_available_for_this_comfort?: number;
  /** number of adults used to calculate the price */
  number_of_adults?: TermsAndConditionsModelV1NumberOfAdults;
  accomodation?: TermsAndConditionAccommodationModelV1;
  departure_city?: DepartureCityV1;
  departure_location?: DepartureLocationModelV1;
  default_price_display?: DefaultPriceDisplay;
  /** indicates whether the displayed price includes fees or not */
  fees_included?: boolean;
  /** Indicates the instalment count: that means on how many instalments the best price can be devided */
  instalment_count?: TermsAndConditionsModelV1InstalmentCount;
  offers?: ProductTermesAndConditionsOffersModel;
}

export type PriceModelV1AnyOf = {
  initial_price?: InitialPriceModelV1;
  best_price?: BestPriceModelV1;
  fee?: ProductFeeModel;
  /**
   * The iso 3 currency. Ex: CNY,EUR,..
   * @minLength 3
   * @maxLength 3
   */
  currency?: string;
  terms_and_conditions?: TermsAndConditionsModelV1;
};

export type PriceModelV1 = PriceModelV1AnyOf | null;

/**
 * range for a tour
 */
export type ProductRangeV1AnyOf = {
  /** range unique id */
  id: string;
  /** range label */
  label: string;
};

/**
 * range for a tour
 */
export type ProductRangeV1 = ProductRangeV1AnyOf | null;

export type ProductLightSeasonsModel =
  (typeof ProductLightSeasonsModel)[keyof typeof ProductLightSeasonsModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductLightSeasonsModel = {
  WINTER: 'WINTER',
  SUMMER: 'SUMMER',
} as const;

/**
 * opening seasons (SUMMER and/or WINTER)
 */
export type SeasonV1 = ProductLightSeasonsModel[];

/**
 * accommodation images
 */
export type AccommodationsImagesV1 = string[];

/**
 * short description of accommodations for this product
 */
export type AccommodationsIntroModelV1AnyOfShortDescription = string | null;

/**
 * global description of restaurants for this product
 */
export type AccommodationsIntroModelV1AnyOfDescription = string | null;

/**
 * number of rooms in the product
 */
export type AccommodationsIntroModelV1AnyOfRoomsCount = number | null;

export type AccommodationsIntroModelV1AnyOf = {
  /** short description of accommodations for this product */
  short_description?: AccommodationsIntroModelV1AnyOfShortDescription;
  /** global description of restaurants for this product */
  description?: AccommodationsIntroModelV1AnyOfDescription;
  images?: AccommodationsImagesV1;
  /** number of rooms in the product */
  rooms_count?: AccommodationsIntroModelV1AnyOfRoomsCount;
};

export type AccommodationsIntroModelV1 = AccommodationsIntroModelV1AnyOf | null;

export interface ProductTag {
  title?: string;
  text_color_id?: string;
  background_color_id?: string;
}

export type ProductTags = ProductTag[];

export type ProductLineModel = (typeof ProductLineModel)[keyof typeof ProductLineModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductLineModel = {
  TOUR: 'TOUR',
  VILLA: 'VILLA',
  CORE: 'CORE',
  EXCLUSIVE_COLLECTION: 'EXCLUSIVE_COLLECTION',
  CRUISE: 'CRUISE',
  JOYVIEW: 'JOYVIEW',
  URBAN_OASIS: 'URBAN_OASIS',
  LODGE: 'LODGE',
} as const;

/**
 * Define the different product lines of a Club Med product
 */
export type ProductsLineModel = ProductLineModel[];

/**
 * customer minimum age welcomed in the product
 * @minimum 0
 */
export type ProductAccessConditionsModelMinAuthorizedAgeInMonths = number | null;

export interface ProductAccessConditionsModel {
  /** "true" if the product is forbidden to children. */
  is_for_adult_only: boolean;
  /**
   * customer minimum age welcomed in the product
   * @minimum 0
   */
  min_authorized_age_in_months?: ProductAccessConditionsModelMinAuthorizedAgeInMonths;
}

/**
 * The ClubMed mobile app supports this product for in resort experience features
 */
export type ClubmedMobileAppModelIsAvailable = boolean | null;

export interface ClubmedMobileAppModel {
  /** The ClubMed mobile app supports this product for in resort experience features */
  is_available?: ClubmedMobileAppModelIsAvailable;
  /** ClubMed Mobile App description */
  description?: string;
}

/**
 * Easy Arrival supports this product for in product experience features

 */
export type ProductEasyArrivalModelIsAvailable = boolean | null;

export interface ProductEasyArrivalModel {
  /** Easy Arrival supports this product for in product experience features
   */
  is_available?: ProductEasyArrivalModelIsAvailable;
  /** ClubMed Mobile App description */
  description?: string;
}

/**
 * arrival date
 */
export type ArrivalDetailsModelAnyOfDate = string | null;

export type ArrivalDetailsModelAnyOf = {
  /** arrival country label */
  country?: string;
  /** arrival city label */
  city?: string;
  /** arrival date */
  date?: ArrivalDetailsModelAnyOfDate;
};

export type ArrivalDetailsModel = ArrivalDetailsModelAnyOf | null;

export interface TripDetailsModel {
  departure_details?: DepartureDetailsModel;
  arrival_details?: ArrivalDetailsModel;
  duration?: DurationModel;
}

export interface DestinationGeographicalModel {
  /** ID of the geographical area for this product */
  id: string;
  /** product geographical area */
  label?: string;
}

export interface Region {
  /** ID of the region for this product */
  id: string;
  /** Label of the region */
  label?: string;
}

export interface ProductDestinationModel {
  geographical_area?: DestinationGeographicalModel;
  countries?: CountriesModelV1;
  region?: Region;
}

export interface Media {
  /** product representative image */
  immersive_image?: string;
  surroundings_images?: SurroundingsImages;
  /** map for the product */
  map?: string;
  /** link to display the product fact sheet */
  fact_sheet_url?: string;
}

/**
 * booking's status
 */
export type BookingStatus = (typeof BookingStatus)[keyof typeof BookingStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BookingStatus = {
  OPTION: 'OPTION',
  CANCELED: 'CANCELED',
  VALIDATED: 'VALIDATED',
  PARTIALLY_VALIDATED: 'PARTIALLY_VALIDATED',
  EXPIRED: 'EXPIRED',
  UNKNOWN: 'UNKNOWN',
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  MUTE: 'MUTE',
  EXPIRED_OPTION: 'EXPIRED_OPTION',
  QUOTATION: 'QUOTATION',
  HOPE: 'HOPE',
  EXPIRED_HOPE: 'EXPIRED_HOPE',
  EXPIRED_QUOTATION: 'EXPIRED_QUOTATION',
  REQUEST: 'REQUEST',
  ARCHIVED: 'ARCHIVED',
} as const;

/**
 * define if this booking was sold by CLUBMED or PARTNERS
 */
export type SoldBy = (typeof SoldBy)[keyof typeof SoldBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SoldBy = {
  CLUBMED: 'CLUBMED',
  PARTNERS: 'PARTNERS',
} as const;

/**
 * type of the vendor
 */
export type VendorTypeModel = (typeof VendorTypeModel)[keyof typeof VendorTypeModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VendorTypeModel = {
  EASY_CLUBMED: 'EASY_CLUBMED',
  CALL_CENTER: 'CALL_CENTER',
  B2C_CHAT: 'B2C_CHAT',
  WEB: 'WEB',
  AGENCY: 'AGENCY',
  FRANCHISE: 'FRANCHISE',
  SHOP: 'SHOP',
  CORPORATE: 'CORPORATE',
  MICE: 'MICE',
  CUSTOMER_ACCOUNT: 'CUSTOMER_ACCOUNT',
  OTHER: 'OTHER',
} as const;

/**
 * name of the vendor
 */
export type VendorModelAnyOfName = string | null;

/**
 * phone number of the vendor
 */
export type VendorModelAnyOfContact = string | null;

export type VendorModelAnyOf = {
  sold_by?: SoldBy;
  /** name of the vendor */
  name?: VendorModelAnyOfName;
  /** phone number of the vendor */
  contact?: VendorModelAnyOfContact;
  type?: VendorTypeModel;
};

export type VendorModel = VendorModelAnyOf | null;

/**
 * The room status
 */
export type Status = (typeof Status)[keyof typeof Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Status = {
  READY: 'READY',
  NOT_READY: 'NOT_READY',
} as const;

/**
 * Room number
 */
export type RoomModelNumber = string | null;

/**
 * Name of the building
 */
export type RoomModelBuilding = string | null;

/**
 * Orientation of the room
 */
export type RoomModelOrientation = string | null;

/**
 * Floor of the room
 */
export type RoomModelFloor = string | null;

export interface RoomModel {
  /** Room number */
  number?: RoomModelNumber;
  /** Name of the building */
  building?: RoomModelBuilding;
  /** Orientation of the room */
  orientation?: RoomModelOrientation;
  /** Floor of the room */
  floor?: RoomModelFloor;
  status?: Status;
  /** indicates whether the room services are available for this room or not.  */
  is_room_intervention_included?: boolean;
}

/**
 * Automatic Option Status: Set as NONE when the proposal is not tagged as to be converted automatically. Displayed as SCHEDULED when the proposal is tagged as to be converted automatically. CONVERTED indicates that the proposal was tagged as to be converted and has been done successfully. On the contrary, FAILED indicates that the proposal was tagged as to be converted but has failed.
 */
export type AutoOptionableStatus = (typeof AutoOptionableStatus)[keyof typeof AutoOptionableStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AutoOptionableStatus = {
  NONE: 'NONE',
  SCHEDULED: 'SCHEDULED',
  CONVERTED: 'CONVERTED',
  FAILED: 'FAILED',
} as const;

/**
 * images of activities of this product
 */
export type ActivitiesImagesV1 = string[];

/**
 * global description of activities for this product
 */
export type ActivitiesIntroModelAnyOfDescription = string | null;

/**
 * short description of activities for this product
 */
export type ActivitiesIntroModelAnyOfShortDescription = string | null;

export type ActivitiesIntroModelAnyOf = {
  /** global description of activities for this product */
  description?: ActivitiesIntroModelAnyOfDescription;
  /** short description of activities for this product */
  short_description?: ActivitiesIntroModelAnyOfShortDescription;
  images?: ActivitiesImagesV1;
};

export type ActivitiesIntroModel = ActivitiesIntroModelAnyOf | null;

export type ProductImagesModel = string[];

/**
 * description of bar extra costs in an all inclusive package
 */
export type BarsDescriptionModelV1Extra = string | null;

/**
 * description of the all inclusive package advantages at the bar
 */
export type BarsDescriptionModelV1Included = string | null;

export interface BarsDescriptionModelV1 {
  /** description of bar extra costs in an all inclusive package */
  extra?: BarsDescriptionModelV1Extra;
  /** description of the all inclusive package advantages at the bar */
  included?: BarsDescriptionModelV1Included;
}

/**
 * global description of bars for this product
 */
export type BarsIntroductionModelV1AnyOfDescription = string | null;

export type BarsIntroductionModelV1AnyOf = {
  /** global description of bars for this product */
  description?: BarsIntroductionModelV1AnyOfDescription;
  images?: ProductImagesModel;
  all_inclusive_description?: BarsDescriptionModelV1;
};

export type BarsIntroductionModelV1 = BarsIntroductionModelV1AnyOf | null;

/**
 * list of the product key points
 */
export type KeyPointsList = string[];

/**
 * Short descritpion of the childcare service in this resort
 */
export type KidActivitiesIntroModelDescription = string | null;

/**
 * Longer description of the childcare service in this resort
 */
export type KidActivitiesIntroModelShortDescription = string | null;

export interface KidActivitiesIntroModel {
  /** Short descritpion of the childcare service in this resort */
  description?: KidActivitiesIntroModelDescription;
  /** Longer description of the childcare service in this resort */
  short_description?: KidActivitiesIntroModelShortDescription;
}

export interface RelatedProductModelV1 {
  id: string;
}

/**
 * list of products for before/during/After trip booking
 */
export type RelatedProductsModelV1 = RelatedProductModelV1[];

/**
 * global description of restaurants for this product
 */
export type RestaurantsIntroModelV1AnyOfDescription = string | null;

export type RestaurantsIntroModelV1AnyOf = {
  /** global description of restaurants for this product */
  description?: RestaurantsIntroModelV1AnyOfDescription;
  images?: ProductImagesModel;
};

export type RestaurantsIntroModelV1 = RestaurantsIntroModelV1AnyOf | null;

/**
 * strengths for the product
 */
export type ProductStrengthsV1 = string[];

/**
 * Longer description of the Spa service in this resort
 */
export type WellnessIntroductionModelAnyOfDescription = string | null;

/**
 * Short description of the Spa service in this resort
 */
export type WellnessIntroductionModelAnyOfShortDescription = string | null;

/**
 * URL of booklet for the Spa of resort
 */
export type WellnessIntroductionModelAnyOfBookletUrl = string | null;

export type WellnessIntroductionModelAnyOf = {
  /** Longer description of the Spa service in this resort */
  description?: WellnessIntroductionModelAnyOfDescription;
  /** Short description of the Spa service in this resort */
  short_description?: WellnessIntroductionModelAnyOfShortDescription;
  /** URL of booklet for the Spa of resort */
  booklet_url?: WellnessIntroductionModelAnyOfBookletUrl;
};

export type WellnessIntroductionModel = WellnessIntroductionModelAnyOf | null;

/**
 * images of Excursions of this product
 */
export type ExcursionsImages = string[];

/**
 * description of Excursions for this product
 */
export type ExcursionIntroductionModelDescription = string | null;

/**
 * short description of Excursions for this product
 */
export type ExcursionIntroductionModelShortDescription = string | null;

export interface ExcursionIntroductionModel {
  /** description of Excursions for this product */
  description?: ExcursionIntroductionModelDescription;
  /** short description of Excursions for this product */
  short_description?: ExcursionIntroductionModelShortDescription;
  images?: ExcursionsImages;
}

/**
 * images of Exclusive Collection range of this product
 */
export type ExclusiveCollectionIntroductionGlobalImagesModel = string[];

export interface ExclusiveCollectionIntroductionGlobalModel {
  /** description of Exclusive Collection range for this product */
  description: string;
  /** short description of Exclusive Collection range for this product */
  short_description: string;
  images: ExclusiveCollectionIntroductionGlobalImagesModel;
}

/**
 * images of the Exclusive Collection space for this product
 */
export type ExclusiveCollectionIntroductionSpecificImagesModel = string[];

export interface ExclusiveCollectionIntroductionStrengthModel {
  /** ID strengths of the Exclusive Collection space for this product */
  id: string;
  /** Label of the strengths of the Exclusive Collection space for this product */
  label: string;
}

export type ExclusiveCollectionIntroductionStrengthsModel =
  ExclusiveCollectionIntroductionStrengthModel[];

export interface ExclusiveCollectionIntroductionSpecificModel {
  /** Title of the Exclusive Collection space for this product */
  title: string;
  /** description of the Exclusive Collection space for this product */
  description: string;
  /** short description of the Exclusive Collection space for this product */
  short_description: string;
  images: ExclusiveCollectionIntroductionSpecificImagesModel;
  strengths: ExclusiveCollectionIntroductionStrengthsModel;
}

export type ExclusiveCollectionIntroductionModelAnyOf = {
  global: ExclusiveCollectionIntroductionGlobalModel;
  specific: ExclusiveCollectionIntroductionSpecificModel;
};

export type ExclusiveCollectionIntroductionModel = ExclusiveCollectionIntroductionModelAnyOf | null;

/**
 * product total surface area in hectares
 */
export type SiteSurfaceAreaValue = number | null;

export interface SiteSurfaceArea {
  /** product total surface area in hectares */
  value?: SiteSurfaceAreaValue;
  /** Site surface area unit */
  unit?: string;
}

export interface ProductCertificationV2Model {
  /** Certification's code */
  code?: string;
  /** Certification's label */
  label?: string;
}

export type Certifications = ProductCertificationV2Model[] | null;

/**
 * maximum capacity of people for this product
 */
export type ProductV2ModelCapacityMax = number | null;

/**
 * main product description
 */
export type ProductV2ModelDescription1 = string | null;

/**
 * secondary product description
 */
export type ProductV2ModelDescription2 = string | null;

/**
 * Further Information for this product
 */
export type ProductV2ModelFurtherInformation = string | null;

export interface ProductV2Model {
  /** Club Med product unique id */
  id: string;
  access_conditions?: ProductAccessConditionsModel;
  areas?: ProductAreasModelV1;
  /** id of product where these lodgings are near for this product */
  associated_product_id?: string;
  available_services?: AvailableServices;
  category?: ProductCategoryModelV1;
  clubmed_mobile_app?: ClubmedMobileAppModel;
  easy_arrival?: ProductEasyArrivalModel;
  comfort?: ProductComfortModelV1;
  trip_details?: TripDetailsModel;
  /** description headline" */
  description_title?: string;
  destination?: ProductDestinationModel;
  /** product full title to be used outside Club Med apps */
  full_title: string;
  media?: Media;
  opening_status: OpeningStatus;
  type?: ProductTypeDetails;
  price?: PriceModelV1;
  /** resort id, deprecated */
  resort_id: string;
  range?: ProductRangeV1;
  seasons?: SeasonV1;
  /** description to be used for seo */
  seo_description?: string;
  /** id of the sibling product open another season, if relevant */
  sibling_id?: string;
  /** product title */
  title: string;
  /** maximum capacity of people for this product */
  capacity_max?: ProductV2ModelCapacityMax;
  tags?: ProductTags;
  product_line?: ProductsLineModel;
  accommodations_introduction?: AccommodationsIntroModelV1;
  activities_introduction?: ActivitiesIntroModel;
  arrival_details?: ArrivalDetailsModel;
  bars_introduction?: BarsIntroductionModelV1;
  /** main product description */
  description_1?: ProductV2ModelDescription1;
  /** secondary product description */
  description_2?: ProductV2ModelDescription2;
  key_points: KeyPointsList;
  kids_activities_introduction: KidActivitiesIntroModel;
  related_products?: RelatedProductsModelV1;
  restaurants_introduction?: RestaurantsIntroModelV1;
  site_surface_area?: SiteSurfaceArea;
  strengths?: ProductStrengthsV1;
  wellness_introduction?: WellnessIntroductionModel;
  /** Further Information for this product */
  further_information?: ProductV2ModelFurtherInformation;
  excursion_introduction?: ExcursionIntroductionModel;
  certifications?: Certifications;
  exclusive_collection_introduction: ExclusiveCollectionIntroductionModel;
  _links?: LinksModel;
}

/**
 * type of fees
 */
export type ProposalPriceFeeModel =
  (typeof ProposalPriceFeeModel)[keyof typeof ProposalPriceFeeModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProposalPriceFeeModel = {
  SUBSCRIPTION: 'SUBSCRIPTION',
  TOURISTIC_TAXES: 'TOURISTIC_TAXES',
  PORT_TAXES: 'PORT_TAXES',
} as const;

export interface FeeModel {
  type: ProposalPriceFeeModel;
  /**
   * amount of fees for this type
   * @minimum 0
   */
  amount: number;
}

/**
 * List of fees
 */
export type FeesModel = FeeModel[];

export interface ProposalTripModel {
  /** Initial price per trip */
  initial_price: number;
  /** Initial price with fees calculated from your criteria */
  initial_price_with_fees: number;
  fees: FeesModel;
}

export interface IncludedServiceModel {
  id: string;
  /** Included service amount applied on the proposal */
  amount: number;
  link?: LinkModel;
  _links?: LinksModel;
}

export type IncludedServicesModel = IncludedServiceModel[];

/**
 * Package option type
 */
export type ProposalServiceTypes = (typeof ProposalServiceTypes)[keyof typeof ProposalServiceTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProposalServiceTypes = {
  CHILDCARE: 'CHILDCARE',
  TRANSFER: 'TRANSFER',
  INSURANCE: 'INSURANCE',
  RENTAL: 'RENTAL',
  EXCURSION: 'EXCURSION',
  WATER_SPORT: 'WATER_SPORT',
  LAND_SPORT: 'LAND_SPORT',
  WINTER_SPORT: 'WINTER_SPORT',
  WELLNESS: 'WELLNESS',
  VISAS: 'VISAS',
  TOURIST_TAX: 'TOURIST_TAX',
  PORT_TAX: 'PORT_TAX',
  CONCIERGERIE: 'CONCIERGERIE',
  PARKING: 'PARKING',
  HONEYMOON: 'HONEYMOON',
  MISCELLANEOUS_VILLAGE: 'MISCELLANEOUS_VILLAGE',
  OTHERS: 'OTHERS',
} as const;

export interface PackageOptionModel {
  type: ProposalServiceTypes;
  /**
   * optional service amount applied on the proposal including discount
   * @minimum 0
   */
  amount: number;
  /**
   * optional service amount applied on the proposal without discount
   * @minimum 0
   */
  amount_without_discount: number;
}

/**
 * Options of package
 */
export type PackageOptionsModel = PackageOptionModel[];

/**
 * Discount type. Possible values: OFFER or SPECIFIC or RATE or SERVICE_OFFER
 */
export type DiscountTypeModel = (typeof DiscountTypeModel)[keyof typeof DiscountTypeModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DiscountTypeModel = {
  OFFER: 'OFFER',
  SPECIFIC: 'SPECIFIC',
  RATE: 'RATE',
  SERVICE_OFFER: 'SERVICE_OFFER',
} as const;

export interface ProposalDiscountModelV1 {
  type: DiscountTypeModel;
  /**
   * Discount's amount applied on the proposal
   * @minimum 0
   */
  amount: number;
  /** Offer code */
  code?: string;
  /** Discount Id. When Id = NRR or FLR, the discount type is a RATE */
  offer_id?: string;
  /** Service id on which the promotion is applied */
  service_id?: string;
  _links?: LinksModel;
}

/**
 * List of discounts applied to the proposal
 */
export type ProposalDiscountsModelV1 = ProposalDiscountModelV1[];

/**
 * Proposal price info
 */
export interface ProposalPriceModelV1 {
  /** Total price(discount_price_with_fees + package_options.price) calculated from your criteria */
  total?: number;
  /** Total price(initial_price_with_fees + package_options.price) calculated from your criteria */
  total_without_discount?: number;
  trip?: ProposalTripModel;
  included_services?: IncludedServicesModel;
  package_options?: PackageOptionsModel;
  /** Total price (discount_price_without_fees) calculated from your criteria. Added services price not included. */
  total_without_fees?: number;
  /**
   * The iso 3 currency. Ex: CNY,EUR,..
   * @minLength 3
   * @maxLength 3
   */
  currency?: string;
  /** Amount of the stay without transport */
  total_without_transport?: number;
  /** Delta between the initial price and the new price computed by the Yield Management */
  yield_pricing_variation?: number;
  discounts?: ProposalDiscountsModelV1;
  /** Indicates if the transfer from the airport to the resort (and vice versa) is included or not. */
  is_transfer_included?: boolean;
}

/**
 * Discount type. Possible value: OFFER, SPECIFIC or SERVICE_OFFER
 */
export type ProposalPriceDiscountModel =
  (typeof ProposalPriceDiscountModel)[keyof typeof ProposalPriceDiscountModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProposalPriceDiscountModel = {
  OFFER: 'OFFER',
  SPECIFIC: 'SPECIFIC',
  SERVICE_OFFER: 'SERVICE_OFFER',
  RATE: 'RATE',
} as const;

export interface DiscountModelV1 {
  type: ProposalPriceDiscountModel;
  /**
   * Discount's amount applied on the proposal
   * @minimum 0
   */
  amount: number;
  /** Offer id if relevant. Only given when the type offer is equal to OFFER */
  offer_id?: string;
  /** Service id on which the promotion is applied */
  service_id?: string;
  /** Offer code */
  code?: string;
  _links?: LinksModel;
}

export type DiscountsModel = DiscountModelV1[];

/**
 * Proposal price info
 */
export interface ProposalPriceModel {
  /** Total price(discount_price_with_fees + package_options.price) calculated from your criteria */
  total?: number;
  /** Total price(initial_price_with_fees + package_options.price) calculated from your criteria */
  total_without_discount?: number;
  discounts?: DiscountsModel;
  trip?: ProposalTripModel;
  included_services?: IncludedServicesModel;
  package_options?: PackageOptionsModel;
  /** Total price (discount_price_without_fees) calculated from your criteria. Added services price not included. */
  total_without_fees?: number;
  /**
   * The iso 3 currency. Ex: CNY,EUR,..
   * @minLength 3
   * @maxLength 3
   */
  currency?: string;
  /** Amount of the stay without transport */
  total_without_transport?: number;
  /** Delta between the initial price and the new price computed by the Yield Management */
  yield_pricing_variation?: number;
}

export interface AccommodationLinkModel {
  id: string;
  /** @minimum 1 */
  quantity?: number;
  /** Indicate if the room is sharable */
  shared_room: boolean;
  link?: LinkModel;
  _links?: LinksModel;
}

/**
 * List of accommodations
 */
export type AccommodationsModel = AccommodationLinkModel[];

export type ProposalOptionDurationModelV1AnyOf = {
  /** Booking expiration date and time */
  expiration_date_time: string;
  /** Indicates if the expiration date is reliable or not. An expiration date is not reliable when the transport is included since it can be cancelled by the transport supplier. The expiration date of a booking without transport is considered as reliable. */
  is_reliable: boolean;
};

export type ProposalOptionDurationModelV1 = ProposalOptionDurationModelV1AnyOf | null;

/**
 * customer's status
 */
export type ProposalResponseCustomerTypeModel =
  (typeof ProposalResponseCustomerTypeModel)[keyof typeof ProposalResponseCustomerTypeModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProposalResponseCustomerTypeModel = {
  NEW_CUSTOMER: 'NEW_CUSTOMER',
  PROSPECT: 'PROSPECT',
  CLIENT: 'CLIENT',
} as const;

/**
 * attendee birthdate (YYYYMMDD)
 */
export type AttendeeModelBirthdate = string | null;

export interface AttendeeModel {
  id?: string;
  /** attendee birthdate (YYYYMMDD) */
  birthdate?: AttendeeModelBirthdate;
  /** customer id of the attendee */
  customer_id?: string;
  customer_type?: ProposalResponseCustomerTypeModel;
}

export type Attendees = AttendeeModel[];

export interface HouseholdModel {
  attendees?: Attendees;
}

export type ProposalHouseholdsModelV1 = HouseholdModel[];

/**
 * transportation way
 */
export type Way = (typeof Way)[keyof typeof Way];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Way = {
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND',
} as const;

/**
 * transportation type. First one if many
 */
export type TransportationType = (typeof TransportationType)[keyof typeof TransportationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransportationType = {
  PLANE: 'PLANE',
  TRAIN: 'TRAIN',
  BOAT: 'BOAT',
  UNKNOWN: 'UNKNOWN',
} as const;

/**
 * used to determine which cancellation policy is to be applied to this travel
 */
export type CancellationPolicyTypeModel =
  (typeof CancellationPolicyTypeModel)[keyof typeof CancellationPolicyTypeModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CancellationPolicyTypeModel = {
  AUCUN: 'AUCUN',
  THEO: 'THEO',
  WEBTHEO: 'WEBTHEO',
  NDC: 'NDC',
  NDCx: 'NDCx',
} as const;

/**
 * Date of the first outward flight if transport, date of arrival in first stay if not, YYYYMMDD
 */
export type ProposalResponseTransportationSummaryModelV1DepartureDate = string | null;

/**
 * Date of transport end, could be arrival at home or to an other stay. Ex: 20160117. Date format YYYYMMDD
 */
export type ProposalResponseTransportationSummaryModelV1ArrivalDate = string | null;

/**
 * Summary of transportation details such as city, date, and type of travel
 */
export interface ProposalResponseTransportationSummaryModelV1 {
  way: Way;
  /** transportation departure city */
  departure_city: string;
  /**  transportation final arrival city */
  arrival_city: string;
  transportation_type: TransportationType;
  cancellation_policy_type: CancellationPolicyTypeModel;
  /** indicates if clubmed transfer from the airport to the resort is included or not. */
  is_transfer_included: boolean;
  /** true if the transport has been purchased by ClubMed */
  clubmed_transport: boolean;
  /** Date of the first outward flight if transport, date of arrival in first stay if not, YYYYMMDD */
  departure_date: ProposalResponseTransportationSummaryModelV1DepartureDate;
  /** Date of transport end, could be arrival at home or to an other stay. Ex: 20160117. Date format YYYYMMDD */
  arrival_date: ProposalResponseTransportationSummaryModelV1ArrivalDate;
}

/**
 * list of transportation summaries
 */
export type ProposalTransportationSummaryModelV1 = ProposalResponseTransportationSummaryModelV1[];

export interface ProposalResponseVendorModel {
  /** Salesman id number */
  salesman_id?: string;
}

export type ProposalResponseModelV1BookingId = number | null;

/**
 * Locale with ISO 639-1 language and ISO 3166-1 country
 */
export type ProposalResponseModelV1Locale = string | null;

export interface ProposalResponseModelV1 {
  /**
   * Proposal identifier
   * @pattern ^\d+$
   */
  id: string;
  /** ClubMed Product identifier */
  product_id: string;
  booking_id?: ProposalResponseModelV1BookingId;
  /** a package_id from /products/{product_id}/packages resource */
  package_id: string;
  label: string;
  /** Resort arrival date. Ex: 20160117. Date format YYYYMMDD */
  resort_arrival_date: string;
  /** Resort departure date. Ex: 20160123. Date format YYYYMMDD */
  resort_departure_date: string;
  price?: ProposalPriceModelV1;
  /** Journey duration */
  duration?: number;
  alternative_price?: ProposalPriceModel;
  accommodations: AccommodationsModel;
  /**
   * count of remaining stock. Can be usefull for stress marketing
   * @minimum 0
   */
  remaining_stock: number;
  /** true if the associated booking can be created with OPTION status */
  option_available: boolean;
  option_durability?: ProposalOptionDurationModelV1;
  households?: ProposalHouseholdsModelV1;
  /** Locale with ISO 639-1 language and ISO 3166-1 country */
  locale: ProposalResponseModelV1Locale;
  _links?: LinksModel;
  transportation_summary?: ProposalTransportationSummaryModelV1;
  /** if true means that the proposal will exist during 6 months (15 days if false) */
  extend_persistence?: boolean;
  auto_optionable_status: AutoOptionableStatus;
  /** Indicates wether the proposal can be transformed into a booking or not. Always displayed as false when attendees are not added. */
  is_bookable: boolean;
  /** proposal creation date time */
  creation_date_time?: string;
  vendor?: ProposalResponseVendorModel;
}

export type StayAccommodationRoomsModel = RoomModel[];

/**
 * accommodation occupancy start date
 */
export type StayAccommodationModelStartDate = string | null;

/**
 * accommodation occupancy end date
 */
export type StayAccommodationModelEndDate = string | null;

/**
 * false if there is no baby bed in the room
 */
export type StayAccommodationModelBabyBed = boolean | null;

/**
 * Indicate if the room is sharable
 */
export type StayAccommodationModelSharedRoom = boolean | null;

/**
 * number of persons in the room
 */
export type StayAccommodationModelOccupation = 0 | null;

export interface StayAccommodationModel {
  /** accommodation occupancy start date */
  start_date?: StayAccommodationModelStartDate;
  /** accommodation occupancy end date */
  end_date?: StayAccommodationModelEndDate;
  /** number of accommodations for the id and time period */
  quantity: number;
  /** false if there is no baby bed in the room */
  baby_bed?: StayAccommodationModelBabyBed;
  /** Indicate if the room is sharable */
  shared_room?: StayAccommodationModelSharedRoom;
  /** number of persons in the room */
  occupation?: StayAccommodationModelOccupation;
  /** accommodation id */
  accommodation_id?: string;
  rooms?: StayAccommodationRoomsModel;
  _links?: LinksModel;
}

export type StayAccommodationsModel = StayAccommodationModel[];

/**
 * List of attendee
 */
export type BookingPackageAttendeeIdsModel = string[];

/**
 * package label
 */
export type BookingPackageModelLabel = string | null;

export interface BookingPackageModel {
  /** package id of the booking */
  id: string;
  /** package label */
  label?: BookingPackageModelLabel;
  attendee_ids?: BookingPackageAttendeeIdsModel;
  _links?: LinksModel;
}

export type BookingPackagesModel = BookingPackageModel[];

/**
 * Indicates if the expiration date is reliable or not. An expiration date is not reliable when the transport is included since it can be cancelled by the transport supplier. The expiration date of a booking without transport is considered as reliable.
 */
export type OptionDurabilityAnyOfIsReliable = boolean | null;

export type OptionDurabilityAnyOf = {
  /** Indicates if the expiration date is reliable or not. An expiration date is not reliable when the transport is included since it can be cancelled by the transport supplier. The expiration date of a booking without transport is considered as reliable. */
  is_reliable?: OptionDurabilityAnyOfIsReliable;
  /** Booking expiration date and time */
  expiration_date_time?: string;
};

export type OptionDurability = OptionDurabilityAnyOf | null;

/**
 * Indicates if this option has been renewed or not
 */
export type CustomerBookingRenewalModelAnyOfHasBeenRenewed = boolean | null;

/**
 * Indicates if this booking or option has been created by option renewal process
 */
export type CustomerBookingRenewalModelAnyOfIsFromRenewal = boolean | null;

export type CustomerBookingRenewalModelAnyOf = {
  /** Indicates if this option has been renewed or not */
  has_been_renewed?: CustomerBookingRenewalModelAnyOfHasBeenRenewed;
  /** Indicates if this booking or option has been created by option renewal process */
  is_from_renewal?: CustomerBookingRenewalModelAnyOfIsFromRenewal;
};

export type CustomerBookingRenewalModel = CustomerBookingRenewalModelAnyOf | null;

/**
 * booking payment's status
 */
export type CustomerBookingPaymentStatusModel =
  (typeof CustomerBookingPaymentStatusModel)[keyof typeof CustomerBookingPaymentStatusModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerBookingPaymentStatusModel = {
  PAID: 'PAID',
  UNPAID: 'UNPAID',
  IN_CREDIT: 'IN_CREDIT',
  PENDING: 'PENDING',
  UNKNOWN: 'UNKNOWN',
} as const;

export type TotalPriceAnyOf = {
  /** Indicates the total price of the booking */
  amount: number;
  /**
   * The iso 3 currency. Ex: CNY,EUR,..
   * @minLength 3
   * @maxLength 3
   */
  currency: string;
};

export type TotalPrice = TotalPriceAnyOf | null;

export type StayAttendeeIdsModel = string[];

/**
 * adult attendees number
 */
export type BookingStayAttendeeAdultsCount =
  (typeof BookingStayAttendeeAdultsCount)[keyof typeof BookingStayAttendeeAdultsCount];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BookingStayAttendeeAdultsCount = {
  NUMBER_0: 0,
} as const;

/**
 * children attendees number
 */
export type BookingStayAttendeeChildrenCount =
  (typeof BookingStayAttendeeChildrenCount)[keyof typeof BookingStayAttendeeChildrenCount];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BookingStayAttendeeChildrenCount = {
  NUMBER_0: 0,
} as const;

/**
 * arrival date for this group of attendees YYYYMMDD
 */
export type BookingStayAttendeeStartDate = string | null;

/**
 * leaving date for this group of attendees YYYYMMDD
 */
export type BookingStayAttendeeEndDate = string | null;

export interface BookingStayAttendee {
  /** adult attendees number */
  adults_count?: BookingStayAttendeeAdultsCount;
  /** children attendees number */
  children_count?: BookingStayAttendeeChildrenCount;
  _links?: LinksModel;
  /** arrival date for this group of attendees YYYYMMDD */
  start_date?: BookingStayAttendeeStartDate;
  /** leaving date for this group of attendees YYYYMMDD */
  end_date?: BookingStayAttendeeEndDate;
  attendee_ids?: StayAttendeeIdsModel;
}

export type BookingStayAttendees = BookingStayAttendee[];

/**
 * Transportation mode
 */
export type CustomerBookingStayOutwardTripTransportationModeModelV2 =
  (typeof CustomerBookingStayOutwardTripTransportationModeModelV2)[keyof typeof CustomerBookingStayOutwardTripTransportationModeModelV2];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerBookingStayOutwardTripTransportationModeModelV2 = {
  PLANE: 'PLANE',
  TRAIN: 'TRAIN',
  BOAT: 'BOAT',
  UNKNOWN: 'UNKNOWN',
} as const;

export type TransportationsOutwardTrip = CustomerBookingStayOutwardTripTransportationModeModelV2[];

/**
 * city of departure
 */
export type OutwardTripModelV2AnyOfDepartureCity = string | null;

/**
 * city of arrival
 */
export type OutwardTripModelV2AnyOfArrivalCity = string | null;

export type OutwardTripModelV2AnyOf = {
  /** city of departure */
  departure_city?: OutwardTripModelV2AnyOfDepartureCity;
  /** city of arrival */
  arrival_city?: OutwardTripModelV2AnyOfArrivalCity;
  transportation?: TransportationsOutwardTrip;
};

export type OutwardTripModelV2 = OutwardTripModelV2AnyOf | null;

/**
 * resort arrival date which can be different from the departure_date, if the flight lasts more than 1 day for example YYYYMMDD
 */
export type CustomerBookingStayModelV2ResortArrivalDate = string | null;

/**
 * resort leaving date, YYYYMMDD
 */
export type CustomerBookingStayModelV2ResortLeavingDate = string | null;

/**
 * Total number of adults for the stay
 */
export type CustomerBookingStayModelV2TotalAdultsCount =
  (typeof CustomerBookingStayModelV2TotalAdultsCount)[keyof typeof CustomerBookingStayModelV2TotalAdultsCount];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerBookingStayModelV2TotalAdultsCount = {
  NUMBER_0: 0,
} as const;

/**
 * Total number of children for the stay
 */
export type CustomerBookingStayModelV2TotalChildrenCount =
  (typeof CustomerBookingStayModelV2TotalChildrenCount)[keyof typeof CustomerBookingStayModelV2TotalChildrenCount];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerBookingStayModelV2TotalChildrenCount = {
  NUMBER_0: 0,
} as const;

/**
 * false if no upsell can be applied to this booking using the api
 */
export type CustomerBookingStayModelV2ApiUpsellAvailable = boolean | null;

export interface CustomerBookingStayModelV2 {
  /** stay id */
  id?: string;
  /** product concerned by the booking */
  product_id?: string;
  /** Label (name of product) */
  label?: string;
  product_type?: ProductTypeModel;
  /** resort arrival date which can be different from the departure_date, if the flight lasts more than 1 day for example YYYYMMDD */
  resort_arrival_date?: CustomerBookingStayModelV2ResortArrivalDate;
  /** resort leaving date, YYYYMMDD */
  resort_leaving_date?: CustomerBookingStayModelV2ResortLeavingDate;
  /** duration of the stay */
  duration?: number;
  attendees?: BookingStayAttendees;
  /** Total number of adults for the stay */
  total_adults_count?: CustomerBookingStayModelV2TotalAdultsCount;
  /** Total number of children for the stay */
  total_children_count?: CustomerBookingStayModelV2TotalChildrenCount;
  outward_trip?: OutwardTripModelV2;
  /** false if no upsell can be applied to this booking using the api */
  api_upsell_available: CustomerBookingStayModelV2ApiUpsellAvailable;
  accommodations?: StayAccommodationsModel;
  packages?: BookingPackagesModel;
  _links?: LinksModel;
}

/**
 * list of stays
 */
export type CustomerBookingStaysModelV2 = CustomerBookingStayModelV2[];

/**
 * Date of event
 */
export type CustomerBookingEventModelDate = string | null;

export interface CustomerBookingEventModel {
  /** Code of event */
  code: string;
  /** Type of event */
  label: string;
  /** Date of event */
  date: CustomerBookingEventModelDate;
}

/**
 * Events
 */
export type CustomerBookingEventsModel = CustomerBookingEventModel[];

/**
 * booking creation date, YYYYMMDD
 */
export type CustomerBookingModelV3CreationDate = string | null;

/**
 * booking return date: date of last return flight if transport, date of departure of last stay if not. YYYYMMDD
 */
export type CustomerBookingModelV3ReturnDate = string | null;

/**
 * true if the booking is composed of mulitple sales contracts, owned by different customers. Online sale processes are not possible in this case.
 */
export type CustomerBookingModelV3MultipleSaleContracts = boolean | null;

/**
 * Deprecated - Indicates if an option has been renewed or not
 */
export type CustomerBookingModelV3IsRenewedOption = boolean | null;

/**
 * defines if GM's payment is allowed for an agency
 */
export type CustomerBookingModelV3AllowedToPay = boolean | null;

/**
 * Language/Country the booking has been created with
 */
export type CustomerBookingModelV3Locale = string | null;

export interface CustomerBookingModelV3 {
  /** booking id */
  id: string;
  /** booking creation date, YYYYMMDD */
  creation_date?: CustomerBookingModelV3CreationDate;
  /** booking departure date: date of first outward flight if transport, date of arrival in first stay if not. YYYYMMDD */
  departure_date?: string;
  /** booking return date: date of last return flight if transport, date of departure of last stay if not. YYYYMMDD */
  return_date?: CustomerBookingModelV3ReturnDate;
  /** true if the booking is composed of mulitple sales contracts, owned by different customers. Online sale processes are not possible in this case. */
  multiple_sale_contracts: CustomerBookingModelV3MultipleSaleContracts;
  option_durability?: OptionDurability;
  booking_status?: BookingStatus;
  /** Deprecated - Indicates if an option has been renewed or not */
  is_renewed_option?: CustomerBookingModelV3IsRenewedOption;
  booking_renewal?: CustomerBookingRenewalModel;
  payment_status?: CustomerBookingPaymentStatusModel;
  /** defines if GM's payment is allowed for an agency */
  allowed_to_pay?: CustomerBookingModelV3AllowedToPay;
  total_price?: TotalPrice;
  discounts?: DiscountsModelV3;
  /** Language/Country the booking has been created with */
  locale?: CustomerBookingModelV3Locale;
  vendor?: VendorModel;
  stays?: CustomerBookingStaysModelV2;
  events: CustomerBookingEventsModel;
  _links?: LinksModel;
}

/**
 * Language/Country, as returned by <code>GET&nbsp;/v0/locales</code> ; e.g. "en-US", "fr-FR", "ja-JP"
 */
export type AcceptLanguageParamModel =
  (typeof AcceptLanguageParamModel)[keyof typeof AcceptLanguageParamModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AcceptLanguageParamModel = {
  'fr-FR': 'fr-FR',
  'fr-BE': 'fr-BE',
  'nl-BE': 'nl-BE',
  'de-CH': 'de-CH',
  'fr-CH': 'fr-CH',
  'en-CH': 'en-CH',
  'nl-NL': 'nl-NL',
  'de-DE': 'de-DE',
  'en-IL': 'en-IL',
  'he-IL': 'he-IL',
  'it-IT': 'it-IT',
  'en-SE': 'en-SE',
  'pt-PT': 'pt-PT',
  'en-ZA': 'en-ZA',
  'es-ES': 'es-ES',
  'en-GB': 'en-GB',
  'en-CY': 'en-CY',
  'tr-TR': 'tr-TR',
  'ru-RU': 'ru-RU',
  'uk-UA': 'uk-UA',
  'en-DK': 'en-DK',
  'en-FI': 'en-FI',
  'en-NO': 'en-NO',
  'en-IE': 'en-IE',
  'en-US': 'en-US',
  'es-MX': 'es-MX',
  'fr-CA': 'fr-CA',
  'en-CA': 'en-CA',
  'es-PA': 'es-PA',
  'es-AR': 'es-AR',
  'es-CL': 'es-CL',
  'pt-BR': 'pt-BR',
  'es-CO': 'es-CO',
  'es-PE': 'es-PE',
  'es-VE': 'es-VE',
  'es-UY': 'es-UY',
  'en-CN': 'en-CN',
  'zh-CN': 'zh-CN',
  'zh-TW': 'zh-TW',
  'en-TW': 'en-TW',
  'en-HK': 'en-HK',
  'zh-HK': 'zh-HK',
  'en-AU': 'en-AU',
  'en-ID': 'en-ID',
  'id-ID': 'id-ID',
  'en-IN': 'en-IN',
  'ja-JP': 'ja-JP',
  'ko-KR': 'ko-KR',
  'en-MY': 'en-MY',
  'en-NZ': 'en-NZ',
  'en-SG': 'en-SG',
  'en-TH': 'en-TH',
  'vn-VN': 'vn-VN',
  'de-AT': 'de-AT',
  'ro-RO': 'ro-RO',
  'pl-PL': 'pl-PL',
  'et-EE': 'et-EE',
  'lv-LV': 'lv-LV',
  'en-LB': 'en-LB',
  'fr-MA': 'fr-MA',
  'se-SE': 'se-SE',
  'th-TH': 'th-TH',
  'en-JP': 'en-JP',
  'en-AF': 'en-AF',
  'en-AL': 'en-AL',
  'fr-DZ': 'fr-DZ',
  'fr-AD': 'fr-AD',
  'en-AO': 'en-AO',
  'en-AG': 'en-AG',
  'en-SA': 'en-SA',
  'en-AM': 'en-AM',
  'en-BS': 'en-BS',
  'en-BH': 'en-BH',
  'en-BD': 'en-BD',
  'en-BB': 'en-BB',
  'en-BZ': 'en-BZ',
  'en-BJ': 'en-BJ',
  'en-BM': 'en-BM',
  'en-BT': 'en-BT',
  'en-MM': 'en-MM',
  'es-BO': 'es-BO',
  'es-BW': 'es-BW',
  'en-BN': 'en-BN',
  'en-BG': 'en-BG',
  'en-BI': 'en-BI',
  'en-BF': 'en-BF',
  'en-CM': 'en-CM',
  'fr-CV': 'fr-CV',
  'en-KY': 'en-KY',
  'fr-CF': 'fr-CF',
  'en-SH': 'en-SH',
  'en-CO': 'en-CO',
  'en-KM': 'en-KM',
  'fr-CG': 'fr-CG',
  'en-KR': 'en-KR',
  'en-KP': 'en-KP',
  'en-CR': 'en-CR',
  'fr-CI': 'fr-CI',
  'en-CU': 'en-CU',
  'en-DJ': 'en-DJ',
  'en-DO': 'en-DO',
  'en-DM': 'en-DM',
  'en-EG': 'en-EG',
  'en-SV': 'en-SV',
  'en-AE': 'en-AE',
  'en-EC': 'en-EC',
  'fr-ET': 'fr-ET',
  'en-FJ': 'en-FJ',
  'en-GA': 'en-GA',
  'en-GM': 'en-GM',
  'en-GH': 'en-GH',
  'en-GI': 'en-GI',
  'gr-GR': 'gr-GR',
  'en-GD': 'en-GD',
  'en-GT': 'en-GT',
  'en-GN': 'en-GN',
  'fr-GW': 'fr-GW',
  'en-GQ': 'en-GQ',
  'en-GY': 'en-GY',
  'fr-GP': 'fr-GP',
  'fr-GF': 'fr-GF',
  'en-HT': 'en-HT',
  'en-HN': 'en-HN',
  'en-HU': 'en-HU',
  'fr-IQ': 'fr-IQ',
  'en-IR': 'en-IR',
  'en-IS': 'en-IS',
  'fr-TL': 'fr-TL',
  'en-JM': 'en-JM',
  'en-JO': 'en-JO',
  'en-KZ': 'en-KZ',
  'en-KH': 'en-KH',
  'en-KE': 'en-KE',
  'fr-KI': 'fr-KI',
  'en-KW': 'en-KW',
  'en-LA': 'en-LA',
  'fr-LS': 'fr-LS',
  'en-LR': 'en-LR',
  'en-LY': 'en-LY',
  'en-LI': 'en-LI',
  'fr-LU': 'fr-LU',
  'en-MO': 'en-MO',
  'en-MG': 'en-MG',
  'en-MW': 'en-MW',
  'en-MV': 'en-MV',
  'en-ML': 'en-ML',
  'en-MT': 'en-MT',
  'ma-MA': 'ma-MA',
  'en-MU': 'en-MU',
  'en-MR': 'en-MR',
  'en-YT': 'en-YT',
  'fr-MC': 'fr-MC',
  'en-MN': 'en-MN',
  'fr-MQ': 'fr-MQ',
  'en-MZ': 'en-MZ',
  'en-MD': 'en-MD',
  'fr-PS': 'fr-PS',
  'en-NA': 'en-NA',
  'fr-NR': 'fr-NR',
  'en-NP': 'en-NP',
  'en-NI': 'en-NI',
  'en-NE': 'en-NE',
  'en-NG': 'en-NG',
  'en-NC': 'en-NC',
  'fr-CK': 'fr-CK',
  'en-OM': 'en-OM',
  'en-UG': 'en-UG',
  'en-PK': 'en-PK',
  'en-PA': 'en-PA',
  'en-PG': 'en-PG',
  'es-PY': 'es-PY',
  'en-PH': 'en-PH',
  'fr-PN': 'fr-PN',
  'fr-PF': 'fr-PF',
  'en-PR': 'en-PR',
  'en-QA': 'en-QA',
  'en-RW': 'en-RW',
  'fr-RE': 'fr-RE',
  'fr-BL': 'fr-BL',
  'en-KN': 'en-KN',
  'en-MF': 'en-MF',
  'en-LC': 'en-LC',
  'en-SM': 'en-SM',
  'fr-PM': 'fr-PM',
  'fr-VC': 'fr-VC',
  'fr-SB': 'fr-SB',
  'en-WS': 'en-WS',
  'fr-ST': 'fr-ST',
  'en-SN': 'en-SN',
  'en-SC': 'en-SC',
  'fr-SL': 'fr-SL',
  'fr-SO': 'fr-SO',
  'fr-SD': 'fr-SD',
  'en-LK': 'en-LK',
  'en-SR': 'en-SR',
  'en-SZ': 'en-SZ',
  'en-SY': 'en-SY',
  'en-TZ': 'en-TZ',
  'en-TD': 'en-TD',
  'en-CZ': 'en-CZ',
  'fr-IO': 'fr-IO',
  'fr-TF': 'fr-TF',
  'en-TG': 'en-TG',
  'fr-TO': 'fr-TO',
  'en-TT': 'en-TT',
  'tu-TN': 'tu-TN',
  'en-TC': 'en-TC',
  'fr-TV': 'fr-TV',
  'fr-LB': 'fr-LB',
  'en-VU': 'en-VU',
  'fr-VA': 'fr-VA',
  'en-VG': 'en-VG',
  'en-VN': 'en-VN',
  'en-WF': 'en-WF',
  'en-YE': 'en-YE',
  'fr-YE': 'fr-YE',
  'en-RS': 'en-RS',
  'fr-CD': 'fr-CD',
  'fr-ZM': 'fr-ZM',
  'en-ZW': 'en-ZW',
  'fr-ME': 'fr-ME',
  'fr-FM': 'fr-FM',
  'fr-MH': 'fr-MH',
  'fr-PW': 'fr-PW',
  'en-HR': 'en-HR',
  'en-SI': 'en-SI',
  'en-SK': 'en-SK',
  'en-EE': 'en-EE',
  'en-LT': 'en-LT',
  'en-LV': 'en-LV',
  'en-MK': 'en-MK',
  'en-BA': 'en-BA',
  'en-UZ': 'en-UZ',
  'en-BY': 'en-BY',
  'fr-TJ': 'fr-TJ',
  'en-GE': 'en-GE',
  'en-AZ': 'en-AZ',
  'sk-SK': 'sk-SK',
  'fr-TM': 'fr-TM',
  'es-DO': 'es-DO',
  'fr-TN': 'fr-TN',
} as const;

/**
 * Optional Access Token (bearer)
 */
export type AuthorizationHeaderParamModel = string;

/**
 * Api_key provided by ClubMed API team
 */
export type ApiKeyHeaderParamModel = string;

/**
 * ClubMed Product identifier
 */
export type ProductIdParamModel = string;

/**
 * The prices are the best prices available
 * @summary Provides detailed information regarding a product
 */
export const getV2ProductsProductId = (productId: ProductIdParamModel) => {
  return fetcher<ProductV2Model>({ url: `/v2/products/${productId}`, method: 'GET' });
};

/**
 * @summary Returns the proposal corresponding to the given proposal_id
 */
export const getV2ProposalsProposalId = (proposalId: string) => {
  return fetcher<ProposalResponseModelV1>({ url: `/v2/proposals/${proposalId}`, method: 'GET' });
};

/**
 * @summary details of one booking
 */
export const getV3CustomersCustomerIdBookingsBookingId = (
  customerId: string,
  bookingId: string,
) => {
  return fetcher<CustomerBookingModelV3>({
    url: `/v3/customers/${customerId}/bookings/${bookingId}`,
    method: 'GET',
  });
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetV2ProductsProductIdResult = NonNullable<
  Awaited<ReturnType<typeof getV2ProductsProductId>>
>;
export type GetV2ProposalsProposalIdResult = NonNullable<
  Awaited<ReturnType<typeof getV2ProposalsProposalId>>
>;
export type GetV3CustomersCustomerIdBookingsBookingIdResult = NonNullable<
  Awaited<ReturnType<typeof getV3CustomersCustomerIdBookingsBookingId>>
>;
