/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Api documentation
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type { PaymentScheduleOutputModel, VersionInfo } from './index.schemas';

export const getPaymentScheduleControllerGetPaymentSchedulesResponseMock =
  (): PaymentScheduleOutputModel[] =>
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
      amount: faker.helpers.arrayElement([
        faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
        undefined,
      ]),
      currency: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      deadline: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      balance: faker.helpers.arrayElement([
        faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
        undefined,
      ]),
    }));

export const getVersionControllerGetResponseMock = (
  overrideResponse: Partial<VersionInfo> = {},
): VersionInfo => ({
  branch: faker.string.alpha({ length: { min: 1, max: 20 } }),
  version: faker.string.alpha({ length: { min: 1, max: 20 } }),
  ...overrideResponse,
});

export const getPaymentScheduleControllerGetPaymentSchedulesMockHandler = (
  overrideResponse?:
    | PaymentScheduleOutputModel[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PaymentScheduleOutputModel[]> | PaymentScheduleOutputModel[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/rest/payment_schedules/:type/:id',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getPaymentScheduleControllerGetPaymentSchedulesResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getVersionControllerGetMockHandler = (
  overrideResponse?:
    | VersionInfo
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<VersionInfo> | VersionInfo),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/rest/version',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getVersionControllerGetResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};
export const getApiDocumentationMock = () => [
  getPaymentScheduleControllerGetPaymentSchedulesMockHandler(),
  getVersionControllerGetMockHandler(),
];
