/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Api documentation
 * OpenAPI spec version: 1.0.0
 */
import type {
  ActionResolverControllerResolveActionParams,
  PaymentConfig,
  PaymentProvidersControllerGetPaymentProviders200,
  PaymentProvidersControllerGetPaymentProvidersParams,
  PaymentScheduleControllerGetPaymentSchedulesParams,
  PaymentScheduleOutputModel,
  ResolvedActionModel,
  VersionInfo,
} from './index.schemas';

import { fetcher } from '../../utils/fetcher';

/**
 * @summary Resolve the payment action for a booking or proposal
 */
export const actionResolverControllerResolveAction = (
  type: 'booking' | 'proposal',
  id: string,
  params?: ActionResolverControllerResolveActionParams,
) => {
  return fetcher<ResolvedActionModel>({
    url: `/rest/action_resolver/${type}/${id}`,
    method: 'GET',
    params,
  });
};

/**
 * @summary Get payment configuration for a given locale and issuer type
 */
export const paymentConfigControllerGetPaymentConfig = () => {
  return fetcher<PaymentConfig>({ url: `/rest/payment_config`, method: 'GET' });
};

/**
 * @summary Get payment providers for a booking or proposal
 */
export const paymentProvidersControllerGetPaymentProviders = (
  type: 'booking' | 'proposal',
  id: string,
  params?: PaymentProvidersControllerGetPaymentProvidersParams,
) => {
  return fetcher<PaymentProvidersControllerGetPaymentProviders200>({
    url: `/rest/payment_providers/${type}/${id}`,
    method: 'GET',
    params,
  });
};

/**
 * @summary Get payment schedules by type and id
 */
export const paymentScheduleControllerGetPaymentSchedules = (
  type: 'booking' | 'proposal',
  id: string,
  params?: PaymentScheduleControllerGetPaymentSchedulesParams,
) => {
  return fetcher<PaymentScheduleOutputModel[]>({
    url: `/rest/payment_schedules/${type}/${id}`,
    method: 'GET',
    params,
  });
};

export const versionControllerGet = () => {
  return fetcher<VersionInfo>({ url: `/rest/version`, method: 'GET' });
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type ActionResolverControllerResolveActionResult = NonNullable<
  Awaited<ReturnType<typeof actionResolverControllerResolveAction>>
>;
export type PaymentConfigControllerGetPaymentConfigResult = NonNullable<
  Awaited<ReturnType<typeof paymentConfigControllerGetPaymentConfig>>
>;
export type PaymentProvidersControllerGetPaymentProvidersResult = NonNullable<
  Awaited<ReturnType<typeof paymentProvidersControllerGetPaymentProviders>>
>;
export type PaymentScheduleControllerGetPaymentSchedulesResult = NonNullable<
  Awaited<ReturnType<typeof paymentScheduleControllerGetPaymentSchedules>>
>;
export type VersionControllerGetResult = NonNullable<
  Awaited<ReturnType<typeof versionControllerGet>>
>;
