/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Api documentation
 * OpenAPI spec version: 1.0.0
 */
export interface PaymentScheduleOutputModel {
  amount?: number;
  currency?: string;
  deadline?: string;
  balance?: number;
}

export interface VersionInfo {
  /** @minLength 1 */
  branch: string;
  /** @minLength 1 */
  version: string;
}

export type PaymentScheduleControllerGetPaymentSchedulesParams = {
  action?: string;
  customer_id?: string;
};
