/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Api documentation
 * OpenAPI spec version: 1.0.0
 */
import type {
  PaymentScheduleControllerGetPaymentSchedulesParams,
  PaymentScheduleOutputModel,
  VersionInfo,
} from './index.schemas';

import { fetcher } from '../../utils/fetcher';

/**
 * @summary Get payment schedules by type and id
 */
export const paymentScheduleControllerGetPaymentSchedules = (
  type: string,
  id: string,
  params?: PaymentScheduleControllerGetPaymentSchedulesParams,
) => {
  return fetcher<PaymentScheduleOutputModel[]>({
    url: `/rest/payment_schedules/${type}/${id}`,
    method: 'GET',
    params,
  });
};

export const versionControllerGet = () => {
  return fetcher<VersionInfo>({ url: `/rest/version`, method: 'GET' });
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type PaymentScheduleControllerGetPaymentSchedulesResult = NonNullable<
  Awaited<ReturnType<typeof paymentScheduleControllerGetPaymentSchedules>>
>;
export type VersionControllerGetResult = NonNullable<
  Awaited<ReturnType<typeof versionControllerGet>>
>;
