/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Oney Marketing API
 * This Open API spec defines the marketing REST API provided by Oney and intended for the merchant. All products are concerned by this specification.

#### Rate limit and cache system:
The simulation service has a dedicated rate limit in order to avoid an overload of the server. This rate limit is
attached to your dedicated API key.
To not reach your limit, Oney advise to realize a cache system on your servers to keep the result of a simulation
for next 24 hours.
- Limit per minute: 600 calls
- Limit per days: 300 000 calls

### Try our API in Sandbox mode 

If you want to try out our API on sandbox mode, please use the following data for Authorization:
- **X-Oney-Authorization**: `121c7c799ccc4bfcb9a5c53cc41dfa15`
- **X-Oney-Partner-Country-Code**: `IT`

In the request, use the following data to identify the sandbox merchant :
- `merchant_guid` =  `678e2eaa-b73d-4dd6-aa4f-7b712d9566e4`
- `psp_guid` = `939a0210-18e5-46ce-8e24-1d64d693dd19` 
 * OpenAPI spec version: 1.1
 */
import { oneyFetcher } from '../fetcher.js';
/**
 * Object describing available insurance data
 */
export interface AvailableInsurances {
  /** Insurance code */
  insurance_code?: string;
  /** Insurance label */
  insurance_label?: string;
}

export interface AvaliableInsurancesRecord {
  Avaliable_insurances?: AvailableInsurances;
}

/**
 * Commercial offer type.
 */
export type BusinessTransactionDetailsBusinessTransactionType =
  (typeof BusinessTransactionDetailsBusinessTransactionType)[keyof typeof BusinessTransactionDetailsBusinessTransactionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BusinessTransactionDetailsBusinessTransactionType = {
  PNFCB: 'PNFCB',
  AFFECTE: 'AFFECTE',
  NONAMORTISSABLE: 'NONAMORTISSABLE',
} as const;

/**
 * Object containing business transaction details
 */
export interface BusinessTransactionDetails {
  /** Commercial code that identifies the offer */
  business_transaction_code: string;
  /** Commercial offer version number */
  business_transaction_version: number;
  /** A short label describing the offer */
  short_label: string;
  /** A longer label describing the offer */
  long_label: string;
  /** Business transaction customer label */
  customer_label: string;
  /** Business transaction usage example */
  example?: string;
  /** Business transaction validity period start date: it cannot be used before this date */
  validity_start_date?: string;
  /** Business transaction validity period end date: it cannot be used after this date */
  validity_end_date?: string;
  /** Commercial offer type. */
  business_transaction_type?: BusinessTransactionDetailsBusinessTransactionType;
  /** Business transaction state. Possible values:
  - A = Active
  - P = Prepared
  - V = Validate
  - I = Inactive
 */
  business_transaction_state?: string;
}

/**
 * Commercial offer type.
 */
export type BusinessTransactionResponseBusinessTransactionType =
  (typeof BusinessTransactionResponseBusinessTransactionType)[keyof typeof BusinessTransactionResponseBusinessTransactionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BusinessTransactionResponseBusinessTransactionType = {
  PNFCB: 'PNFCB',
  AFFECTE: 'AFFECTE',
  NONAMORTISSABLE: 'NONAMORTISSABLE',
} as const;

/**
 * Object containing Business Transaction data
 */
export interface BusinessTransactionResponse {
  /** Commercial code that identifies the offer */
  business_transaction_code: string;
  /** Commercial offer version number */
  business_transaction_version: number;
  /** A short label describing the offer */
  short_label: string;
  /** A longer label describing the offer */
  long_label: string;
  /** Business transaction customer label */
  customer_label: string;
  /** Commercial offer type. */
  business_transaction_type: BusinessTransactionResponseBusinessTransactionType;
  /** Minimum number of instalments for this business transaction */
  minimum_number_of_instalments: number;
  /** Maximum number of instalments for this business transaction */
  maximum_number_of_instalments: number;
  /** Minimum amount allowed for this business transaction */
  minimum_selling_price: number;
  /** Maximum amount allowed for this business transaction */
  maximum_selling_price: number;
  /** Specify any discount_rate applied if any. */
  discount_rate: number;
  /** true if the number of instalments can be chosen, otherwise false */
  choosable_number_of_instalments: boolean;
  /** true if this business transaction is free of cost to the customer */
  free_business_transaction: boolean;
  /** Business transaction usage example */
  example?: string;
  /** Business transaction validity period start date: it cannot be used before this date */
  validity_start_date?: string;
  /** Business transaction validity period end date: it cannot be used after this date */
  validity_end_date?: string;
  /** Number of months the business transaction is postponed */
  postponement_duration_in_months?: number;
  /** Display order of the business transaction on a payment terminal */
  display_order?: number;
  avaliable_insurances?: AvaliableInsurancesRecord[];
}

/**
 * Object containing business transaction details
 */
export type ContractSimulationBusinessTransactionDetails = { [key: string]: unknown };

export interface ContractSimulation {
  /** Simulation amount */
  payment_amount: number;
  /** Effective Annual percentage rate for simulation */
  effective_annual_percentage_rate: number;
  /** Total amount of administrative fees */
  administration_fee_amount: number;
  /** Total cost of the credit (`admnistration_fee_amount` + `accrued_interest_amount` + `insurance_amount`) */
  total_cost: number;
  /** Interest total amount */
  accrued_interest_amount?: number;
  /** Insurance total amount */
  insurance_amount?: number;
  /** Provision amount (first payment) */
  down_payment_amount: number;
  /** Nominal annual percentage rate for the simulation */
  nominal_annual_percentage_rate: number;
  /** Insurance annual percentage rate for the simulation */
  insurance_annual_percentage_rate?: number;
  /** First instalment date (format yyyy-MM-dd) */
  first_instalment_date: string;
  /** List containing all the instalments for the simulation */
  instalments?: InstalmentItem[];
  /** Object containing business transaction details */
  business_transaction_details?: ContractSimulationBusinessTransactionDetails;
}

/**
 * Obect containing info about the instalment
 */
export interface InstalmentItem {
  /** Total installment amount (with interest and insurance amounts) */
  instalment_amount: number;
  insurance_amount: number;
  interest_amount: number;
  instalment_number: number;
  collection_date: string;
  administration_fee_amount?: number;
}

export type PaymentsErrorErrorsItem = {
  /**
   * Error code
   * @maxLength 10
   */
  subcode?: string;
  /**
   * Error explanation
   * @maxLength 1000
   */
  label?: string;
};

/**
 * Object containing data describing the occurred error
 */
export interface PaymentsError {
  /** Field which is causing the error */
  errors?: PaymentsErrorErrorsItem[];
}

export type BusinessTransactionParams = {
  /**
   * Merchant global unique identifier given by Oney to the partner
   * @maxLength 100
   */
  merchant_guid: string;
  /**
   * PSP unique identifier
   * @maxLength 100
   */
  psp_guid?: string;
  /**
 * Commercial offer type. Possible values:
- PNFCB: it refer to 3x4x business transactions 
- AFFECTE: it refer to specific purpose loan
- NONAMORTISSABLE: it refer to revolving loan

 * @maxLength 20
 */
  business_transaction_type?: string;
  /**
   * Amount of asked payment. Acts as a filter which removes business transactions incompatible with the requested amount.
   */
  payment_amount?: number;
  /**
   * Free for customer business transaction. Acts as a filter which only shows free or not free business transactions.
   */
  free_business_transaction?: boolean;
  /**
   * If business transaction has a validity period, it filters on date filled.
   */
  start_date?: string;
  /**
   * If business transaction has a validity period, it filters on date filled.
   */
  end_date?: string;
};

export type SimulationParams = {
  /**
   * Merchant global unique identifier given by Oney to the partner
   * @maxLength 100
   */
  merchant_guid: string;
  /**
   * PSP unique identifier
   * @maxLength 100
   */
  psp_guid: string;
  /**
   * Commercial code to identify the offer
   */
  business_transaction_code: string;
  /**
   * Commercial offer version number
   */
  business_transaction_version?: number;
  /**
   * Amount of asked payment
   */
  payment_amount: number;
  /**
   * ISO 4217 currency code of the amount
   */
  currency?: string;
  /**
   * Requested loan's duration in months. This parameter is mandatory if the business transaction's maximum and minimum number of instalments are different
   */
  duration?: number;
  /**
   * Requested insurance code to be proposed in the simulation
   * @maxLength 5
   */
  insurance_code?: string;
  /**
 * Commercial offer type. Possible values:
- PNFCB: it refer to 3x4x business transactions 
- AFFECTE: it refer to specific purpose loan
- NONAMORTISSABLE: it refer to revolving loan

 * @maxLength 20
 */
  business_transaction_type?: string;
  /**
   * Free for customer business transaction. Acts as a filter which only shows free or not free business transactions.
   */
  free_business_transaction?: boolean;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Business transaction list request to get available transactions
 */
export const businessTransaction = (
  params: BusinessTransactionParams,
  options?: SecondParameter<typeof oneyFetcher<BusinessTransactionResponse[]>>,
) => {
  return oneyFetcher<BusinessTransactionResponse[]>(
    { url: `/product_catalog/v1.1/business_transaction`, method: 'GET', params },
    options,
  );
};

/**
 * This service simulates a loan with your available business transactions.

To determine the business transaction to use in the simulation, there are 2 methods:
1. The business transaction’s code is known :
  - Only the business_transaction_code and payment_amount need to be systematically provided;
  - Duration can be added if necessary
2. The business transaction isn’t known :
  - Filters (business_transaction_type, free_business_transaction, insurance_code, payment_amount, etc.) can be used and the loan simulation service will determine which business transaction fits the requirements best.
 */
export const simulation = (
  params: SimulationParams,
  options?: SecondParameter<typeof oneyFetcher<ContractSimulation>>,
) => {
  return oneyFetcher<ContractSimulation>(
    { url: `/sale_support_tools/v1.1/simulation`, method: 'GET', params },
    options,
  );
};

export type BusinessTransactionResult = NonNullable<
  Awaited<ReturnType<typeof businessTransaction>>
>;
export type SimulationResult = NonNullable<Awaited<ReturnType<typeof simulation>>>;
