/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * ClubMed API
 * Club Med, renowned for its luxury resort experiences, proudly introduces its dedicated API. This tool offers developers a gateway to the diverse services and information provided by Club Med, from vacation bookings to on-site activity details. By using this interface, partners and developers can effortlessly integrate Club Med's offerings into their platforms. Whether you're looking for destination details, making reservations, or discovering the latest promotions, the Club Med API ensures a streamlined user experience. Step into this digital realm and amplify your platforms with the Club Med API.
 * OpenAPI spec version: 0.3450.0
 */
import { fetcher } from '../../http/fetcher.js';
export interface LinkModel {
  /** Name of the relationship */
  rel?: string;
  /** Indicates if the link is deprecated due to unnormalized rel */
  deprecated_rel?: boolean;
  /** Indicates if it is an external link */
  external?: boolean;
  /** HTTP method to use */
  method?: string;
  /** Link to the resource */
  href?: string;
  /** A label for the link */
  label?: string;
}

/**
 * Links
 */
export type LinksModel = LinkModel[];

export interface BadRequestErrorModel {
  error_code?: string;
  concerned_key?: string;
  error_description?: string;
}

export type Errors = BadRequestErrorModel[];

export interface BadRequestModel {
  status_code?: number;
  error?: string;
  error_description?: string;
  errors?: Errors;
}

export interface UnauthorizedModel {
  status_code?: number;
  error?: string;
  error_description?: string;
}

export interface NotFoundModel {
  status_code?: number;
  error?: string;
  error_description?: string;
}

export interface ForbiddenModel {
  status_code?: number;
  error?: string;
  error_description?: string;
}

/**
 * Indicates phone information for this country
 */
export type CountryPhonesModelAnyOf = {
  /** Indicates the international phone calling code for this country */
  calling_code: string;
};

/**
 * Indicates phone information for this country
 */
export type CountryPhonesModel = CountryPhonesModelAnyOf | null;

/**
 * Indicates the language code
 */
export type CountryLanguageModelValue = string | null;

/**
 * Indicates the language code
 */
export type CountryLanguageModelLabel = string | null;

/**
 * Indicates the language locale
 */
export type CountryLanguageModelLocale = string | null;

export interface CountryLanguageModel {
  /** Indicates the language code */
  value?: CountryLanguageModelValue;
  /** Indicates the language code */
  label?: CountryLanguageModelLabel;
  /** Indicates the language locale */
  locale?: CountryLanguageModelLocale;
}

export type CountriesLanguageModel = CountryLanguageModel[];

/**
 * Indicates the default language code
 */
export type CountryLanguagesModelDefault = string | null;

export interface CountryLanguagesModel {
  /** Indicates the default language code */
  default: CountryLanguagesModelDefault;
  values: CountriesLanguageModel;
}

/**
 * List of available countries descriptions
 */
export interface CountryModel {
  /** Indicates the country identifier */
  id: string;
  /** Indicates the country label */
  label: string;
  phones?: CountryPhonesModel;
  languages?: CountryLanguagesModel;
}

/**
 * List of available countries descriptions
 */
export type CountriesModel = CountryModel[];

/**
 * Phone type
 */
export type PhoneTypeModel = (typeof PhoneTypeModel)[keyof typeof PhoneTypeModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PhoneTypeModel = {
  HOME: 'HOME',
  MOBILE: 'MOBILE',
  OFFICE: 'OFFICE',
} as const;

export interface PhoneModel {
  /** Phone number */
  number?: string;
  type?: PhoneTypeModel;
}

export type PhonesModel = PhoneModel[];

/**
 * type of product
 */
export type ProductTypeModel = (typeof ProductTypeModel)[keyof typeof ProductTypeModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductTypeModel = {
  CRUISE: 'CRUISE',
  TOUR: 'TOUR',
  JOYVIEW: 'JOYVIEW',
  VILLAGE: 'VILLAGE',
  VILLA: 'VILLA',
  SUMMER_CAMP: 'SUMMER_CAMP',
  URBAN_OASIS: 'URBAN_OASIS',
  LODGE: 'LODGE',
} as const;

export interface DiscountModelV3 {
  /** id of the applied discount on the booking */
  id: string;
}

export type DiscountsModelV3 = DiscountModelV3[];

/**
 * Type of national identifier code, null if not recognized
 */
export type NationalIdentifierCodeTypeModel =
  (typeof NationalIdentifierCodeTypeModel)[keyof typeof NationalIdentifierCodeTypeModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NationalIdentifierCodeTypeModel = {
  CPF: 'CPF',
  CUIL: 'CUIL',
  TAX_NUMBER: 'TAX_NUMBER',
  SECURITY_NUMBER: 'SECURITY_NUMBER',
  ID_NUMBER: 'ID_NUMBER',
  NATIONAL_REGISTER: 'NATIONAL_REGISTER',
  DNI: 'DNI',
} as const;

/**
 * National identifier code
 */
export type NationalIdentifierCodeModelAnyOf = {
  /** National identifier code */
  number: string;
  type: NationalIdentifierCodeTypeModel;
};

/**
 * National identifier code
 */
export type NationalIdentifierCodeModel = NationalIdentifierCodeModelAnyOf | null;

/**
 * Number of installements, 1 is for a full payment at once.
 */
export type TimePaymentConditionModelPaymentCount = number | null;

/**
 * Charge rate to apply when the customer choose this payment condition.
 */
export type TimePaymentConditionModelChargePercentage = number | null;

/**
 * Charge amount to apply when the customer choose this payment condition.
 */
export type TimePaymentConditionModelChargeAmount = number | null;

/**
 * Installment option
 */
export interface TimePaymentConditionModel {
  /** Installment option id */
  id?: string;
  /** Number of installements, 1 is for a full payment at once. */
  payment_count?: TimePaymentConditionModelPaymentCount;
  /** Charge rate to apply when the customer choose this payment condition. */
  charge_percentage?: TimePaymentConditionModelChargePercentage;
  /**
   * Required number of days before the first day of transport when there is one, or the first day in the resort otherwise.
   * @minimum 0
   */
  required_delay_before_departure: number;
  /** Charge amount to apply when the customer choose this payment condition. */
  charge_amount?: TimePaymentConditionModelChargeAmount;
}

/**
 * Sorted list of installment options.
 */
export type TimePaymentConditionListModel = TimePaymentConditionModel[];

/**
 * Free form qualifier of the payment method
 */
export type PaymentMethodModel4Category = string | null;

/**
 * Payment method.
 */
export interface PaymentMethodModel4 {
  /** Payment method id */
  id: string;
  /** Payment method label */
  label?: string;
  /** Url of the payment method logo */
  image?: string;
  /**
   * The iso 3 currency. Ex: CNY,EUR,..
   * @minLength 3
   * @maxLength 3
   */
  currency: string;
  /** Free form qualifier of the payment method */
  category?: PaymentMethodModel4Category;
  time_payment_conditions?: TimePaymentConditionListModel;
}

/**
 * Sorted list of payment methods
 */
export type PaymentMethodListModel2 = PaymentMethodModel4[];

/**
 * Codified value, looking like a bank card brand, required by accountant department.
 */
export type PaymentProvider1CategoryPaymentMethod =
  (typeof PaymentProvider1CategoryPaymentMethod)[keyof typeof PaymentProvider1CategoryPaymentMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentProvider1CategoryPaymentMethod = {
  CreditCard: 'CreditCard',
  BankTransfer: 'BankTransfer',
  DirectDebit: 'DirectDebit',
  BuyNowPayLater: 'BuyNowPayLater',
  Cheque: 'Cheque',
  Paypal: 'Paypal',
  '': '',
} as const;

export interface PaymentProvider1 {
  /**
   * Provider id, the first letter tells the intended integration behavior : <br/>
&rarr; <code>E</code> for a normalized integration involving a redirection or an iframe to a payment form hosted by the provider ;<br/>
&rarr; <code>S</code> for a PSP involving a direct-link type transmission ;<br/>
&rarr; <code>M</code> for a more involved integration with specific developments, with the exception of <code>MCLUBMED</code> that is a manual payment.
   * @pattern ^([EMS][0-9A-Z]+)$
   */
  id: string;
  /** A label for the provider */
  label: string;
  /** Payment processing, may be one of the following : <br/>
&rarr; <code>E-commerce</code> when the payment process occurs directly on the partner site ;<br/>
&rarr; <code>Direct-Link</code> when the payment process is directly managed by the Club Med (data collection and <strong>automatic</strong> transfer to the provider) ;<br/>
&rarr; <code>Not-connected</code> when the payment process is directly managed by the Club Med (data collection and <strong>manual</strong> transfer to the provider) */
  connection_type: string;
  /** Url to the logo of the provider */
  logo?: string;
  /**
   * Required number of days before the first day of transport when there is one, or the first day in the resort otherwise.
   * @minimum 0
   */
  required_delay_before_departure: number;
  /** Codified value, looking like a bank card brand, required by accountant department. */
  category_payment_method: PaymentProvider1CategoryPaymentMethod;
  /** A flag to hint that the billing address should be requested by the web site */
  billing_address_form: boolean;
  /** A text to describe the payment provider */
  description?: string;
  payment_methods?: PaymentMethodListModel2;
}

/**
 * List of payment providers
 */
export type PaymentProviderListModel2 = PaymentProvider1[];

/**
 * booking's status
 */
export type BookingStatus = (typeof BookingStatus)[keyof typeof BookingStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BookingStatus = {
  OPTION: 'OPTION',
  CANCELED: 'CANCELED',
  VALIDATED: 'VALIDATED',
  PARTIALLY_VALIDATED: 'PARTIALLY_VALIDATED',
  EXPIRED: 'EXPIRED',
  UNKNOWN: 'UNKNOWN',
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  MUTE: 'MUTE',
  EXPIRED_OPTION: 'EXPIRED_OPTION',
  QUOTATION: 'QUOTATION',
  HOPE: 'HOPE',
  EXPIRED_HOPE: 'EXPIRED_HOPE',
  EXPIRED_QUOTATION: 'EXPIRED_QUOTATION',
  REQUEST: 'REQUEST',
  ARCHIVED: 'ARCHIVED',
} as const;

/**
 * define if this booking was sold by CLUBMED or PARTNERS
 */
export type SoldBy = (typeof SoldBy)[keyof typeof SoldBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SoldBy = {
  CLUBMED: 'CLUBMED',
  PARTNERS: 'PARTNERS',
} as const;

/**
 * type of the vendor
 */
export type VendorTypeModel = (typeof VendorTypeModel)[keyof typeof VendorTypeModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VendorTypeModel = {
  EASY_CLUBMED: 'EASY_CLUBMED',
  CALL_CENTER: 'CALL_CENTER',
  B2C_CHAT: 'B2C_CHAT',
  WEB: 'WEB',
  AGENCY: 'AGENCY',
  FRANCHISE: 'FRANCHISE',
  SHOP: 'SHOP',
  CORPORATE: 'CORPORATE',
  MICE: 'MICE',
  CUSTOMER_ACCOUNT: 'CUSTOMER_ACCOUNT',
  OTHER: 'OTHER',
} as const;

/**
 * name of the vendor
 */
export type VendorModelAnyOfName = string | null;

/**
 * phone number of the vendor
 */
export type VendorModelAnyOfContact = string | null;

export type VendorModelAnyOf = {
  sold_by?: SoldBy;
  /** name of the vendor */
  name?: VendorModelAnyOfName;
  /** phone number of the vendor */
  contact?: VendorModelAnyOfContact;
  type?: VendorTypeModel;
};

export type VendorModel = VendorModelAnyOf | null;

/**
 * The room status
 */
export type Status = (typeof Status)[keyof typeof Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Status = {
  READY: 'READY',
  NOT_READY: 'NOT_READY',
} as const;

/**
 * Room number
 */
export type RoomModelNumber = string | null;

/**
 * Name of the building
 */
export type RoomModelBuilding = string | null;

/**
 * Orientation of the room
 */
export type RoomModelOrientation = string | null;

/**
 * Floor of the room
 */
export type RoomModelFloor = string | null;

export interface RoomModel {
  /** Room number */
  number?: RoomModelNumber;
  /** Name of the building */
  building?: RoomModelBuilding;
  /** Orientation of the room */
  orientation?: RoomModelOrientation;
  /** Floor of the room */
  floor?: RoomModelFloor;
  status?: Status;
  /** indicates whether the room services are available for this room or not.  */
  is_room_intervention_included?: boolean;
}

/**
 * Automatic Option Status: Set as NONE when the proposal is not tagged as to be converted automatically. Displayed as SCHEDULED when the proposal is tagged as to be converted automatically. CONVERTED indicates that the proposal was tagged as to be converted and has been done successfully. On the contrary, FAILED indicates that the proposal was tagged as to be converted but has failed.
 */
export type AutoOptionableStatus = (typeof AutoOptionableStatus)[keyof typeof AutoOptionableStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AutoOptionableStatus = {
  NONE: 'NONE',
  SCHEDULED: 'SCHEDULED',
  CONVERTED: 'CONVERTED',
  FAILED: 'FAILED',
} as const;

/**
 * Communication channel
 */
export type ValidOptinChanelModel =
  (typeof ValidOptinChanelModel)[keyof typeof ValidOptinChanelModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ValidOptinChanelModel = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  WECHAT: 'WECHAT',
  PHONE: 'PHONE',
  MAIL: 'MAIL',
  ALL: 'ALL',
  FOSUN_PARTNERS: 'FOSUN_PARTNERS',
  CLUBMED_PLUS: 'CLUBMED_PLUS',
  WHATSAPP: 'WHATSAPP',
  PROFILING: 'PROFILING',
  CGU_2: 'CGU_2',
  CONFORMITY: 'CONFORMITY',
} as const;

/**
 * type of fees
 */
export type ProposalPriceFeeModel =
  (typeof ProposalPriceFeeModel)[keyof typeof ProposalPriceFeeModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProposalPriceFeeModel = {
  SUBSCRIPTION: 'SUBSCRIPTION',
  TOURISTIC_TAXES: 'TOURISTIC_TAXES',
  PORT_TAXES: 'PORT_TAXES',
} as const;

export interface FeeModel {
  type: ProposalPriceFeeModel;
  /**
   * amount of fees for this type
   * @minimum 0
   */
  amount: number;
}

/**
 * List of fees
 */
export type FeesModel = FeeModel[];

export interface ProposalTripModel {
  /** Initial price per trip */
  initial_price: number;
  /** Initial price with fees calculated from your criteria */
  initial_price_with_fees: number;
  fees: FeesModel;
}

export interface IncludedServiceModel {
  id: string;
  /** Included service amount applied on the proposal */
  amount: number;
  link?: LinkModel;
  _links?: LinksModel;
}

export type IncludedServicesModel = IncludedServiceModel[];

/**
 * Package option type
 */
export type ProposalServiceTypes = (typeof ProposalServiceTypes)[keyof typeof ProposalServiceTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProposalServiceTypes = {
  CHILDCARE: 'CHILDCARE',
  TRANSFER: 'TRANSFER',
  INSURANCE: 'INSURANCE',
  RENTAL: 'RENTAL',
  EXCURSION: 'EXCURSION',
  WATER_SPORT: 'WATER_SPORT',
  LAND_SPORT: 'LAND_SPORT',
  WINTER_SPORT: 'WINTER_SPORT',
  WELLNESS: 'WELLNESS',
  VISAS: 'VISAS',
  TOURIST_TAX: 'TOURIST_TAX',
  PORT_TAX: 'PORT_TAX',
  CONCIERGERIE: 'CONCIERGERIE',
  PARKING: 'PARKING',
  HONEYMOON: 'HONEYMOON',
  MISCELLANEOUS_VILLAGE: 'MISCELLANEOUS_VILLAGE',
  OTHERS: 'OTHERS',
} as const;

export interface PackageOptionModel {
  type: ProposalServiceTypes;
  /**
   * optional service amount applied on the proposal including discount
   * @minimum 0
   */
  amount: number;
  /**
   * optional service amount applied on the proposal without discount
   * @minimum 0
   */
  amount_without_discount: number;
}

/**
 * Options of package
 */
export type PackageOptionsModel = PackageOptionModel[];

/**
 * Discount type. Possible values: OFFER or SPECIFIC or RATE or SERVICE_OFFER
 */
export type DiscountTypeModel = (typeof DiscountTypeModel)[keyof typeof DiscountTypeModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DiscountTypeModel = {
  OFFER: 'OFFER',
  SPECIFIC: 'SPECIFIC',
  RATE: 'RATE',
  SERVICE_OFFER: 'SERVICE_OFFER',
} as const;

export interface ProposalDiscountModelV1 {
  type: DiscountTypeModel;
  /**
   * Discount's amount applied on the proposal
   * @minimum 0
   */
  amount: number;
  /** Offer code */
  code?: string;
  /** Discount Id. When Id = NRR or FLR, the discount type is a RATE */
  offer_id?: string;
  /** Service id on which the promotion is applied */
  service_id?: string;
  _links?: LinksModel;
}

/**
 * List of discounts applied to the proposal
 */
export type ProposalDiscountsModelV1 = ProposalDiscountModelV1[];

/**
 * Proposal price info
 */
export interface ProposalPriceModelV1 {
  /** Total price(discount_price_with_fees + package_options.price) calculated from your criteria */
  total?: number;
  /** Total price(initial_price_with_fees + package_options.price) calculated from your criteria */
  total_without_discount?: number;
  trip?: ProposalTripModel;
  included_services?: IncludedServicesModel;
  package_options?: PackageOptionsModel;
  /** Total price (discount_price_without_fees) calculated from your criteria. Added services price not included. */
  total_without_fees?: number;
  /**
   * The iso 3 currency. Ex: CNY,EUR,..
   * @minLength 3
   * @maxLength 3
   */
  currency?: string;
  /** Amount of the stay without transport */
  total_without_transport?: number;
  /** Delta between the initial price and the new price computed by the Yield Management */
  yield_pricing_variation?: number;
  discounts?: ProposalDiscountsModelV1;
  /** Indicates if the transfer from the airport to the resort (and vice versa) is included or not. */
  is_transfer_included?: boolean;
}

/**
 * Discount type. Possible value: OFFER, SPECIFIC or SERVICE_OFFER
 */
export type ProposalPriceDiscountModel =
  (typeof ProposalPriceDiscountModel)[keyof typeof ProposalPriceDiscountModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProposalPriceDiscountModel = {
  OFFER: 'OFFER',
  SPECIFIC: 'SPECIFIC',
  SERVICE_OFFER: 'SERVICE_OFFER',
  RATE: 'RATE',
} as const;

export interface DiscountModelV1 {
  type: ProposalPriceDiscountModel;
  /**
   * Discount's amount applied on the proposal
   * @minimum 0
   */
  amount: number;
  /** Offer id if relevant. Only given when the type offer is equal to OFFER */
  offer_id?: string;
  /** Service id on which the promotion is applied */
  service_id?: string;
  /** Offer code */
  code?: string;
  _links?: LinksModel;
}

export type DiscountsModel = DiscountModelV1[];

/**
 * Proposal price info
 */
export interface ProposalPriceModel {
  /** Total price(discount_price_with_fees + package_options.price) calculated from your criteria */
  total?: number;
  /** Total price(initial_price_with_fees + package_options.price) calculated from your criteria */
  total_without_discount?: number;
  discounts?: DiscountsModel;
  trip?: ProposalTripModel;
  included_services?: IncludedServicesModel;
  package_options?: PackageOptionsModel;
  /** Total price (discount_price_without_fees) calculated from your criteria. Added services price not included. */
  total_without_fees?: number;
  /**
   * The iso 3 currency. Ex: CNY,EUR,..
   * @minLength 3
   * @maxLength 3
   */
  currency?: string;
  /** Amount of the stay without transport */
  total_without_transport?: number;
  /** Delta between the initial price and the new price computed by the Yield Management */
  yield_pricing_variation?: number;
}

export interface AccommodationLinkModel {
  id: string;
  /** @minimum 1 */
  quantity?: number;
  /** Indicate if the room is sharable */
  shared_room: boolean;
  link?: LinkModel;
  _links?: LinksModel;
}

/**
 * List of accommodations
 */
export type AccommodationsModel = AccommodationLinkModel[];

export type ProposalOptionDurationModelV1AnyOf = {
  /** Booking expiration date and time */
  expiration_date_time: string;
  /** Indicates if the expiration date is reliable or not. An expiration date is not reliable when the transport is included since it can be cancelled by the transport supplier. The expiration date of a booking without transport is considered as reliable. */
  is_reliable: boolean;
};

export type ProposalOptionDurationModelV1 = ProposalOptionDurationModelV1AnyOf | null;

/**
 * customer's status
 */
export type ProposalResponseCustomerTypeModel =
  (typeof ProposalResponseCustomerTypeModel)[keyof typeof ProposalResponseCustomerTypeModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProposalResponseCustomerTypeModel = {
  NEW_CUSTOMER: 'NEW_CUSTOMER',
  PROSPECT: 'PROSPECT',
  CLIENT: 'CLIENT',
} as const;

/**
 * attendee birthdate (YYYYMMDD)
 */
export type AttendeeModelBirthdate = string | null;

export interface AttendeeModel {
  id?: string;
  /** attendee birthdate (YYYYMMDD) */
  birthdate?: AttendeeModelBirthdate;
  /** customer id of the attendee */
  customer_id?: string;
  customer_type?: ProposalResponseCustomerTypeModel;
}

export type Attendees = AttendeeModel[];

export interface HouseholdModel {
  attendees?: Attendees;
}

export type ProposalHouseholdsModelV1 = HouseholdModel[];

/**
 * transportation way
 */
export type Way = (typeof Way)[keyof typeof Way];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Way = {
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND',
} as const;

/**
 * transportation type. First one if many
 */
export type TransportationType = (typeof TransportationType)[keyof typeof TransportationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransportationType = {
  PLANE: 'PLANE',
  TRAIN: 'TRAIN',
  BOAT: 'BOAT',
  UNKNOWN: 'UNKNOWN',
} as const;

/**
 * used to determine which cancellation policy is to be applied to this travel
 */
export type CancellationPolicyTypeModel =
  (typeof CancellationPolicyTypeModel)[keyof typeof CancellationPolicyTypeModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CancellationPolicyTypeModel = {
  AUCUN: 'AUCUN',
  THEO: 'THEO',
  WEBTHEO: 'WEBTHEO',
  NDC: 'NDC',
  NDCx: 'NDCx',
} as const;

/**
 * Date of the first outward flight if transport, date of arrival in first stay if not, YYYYMMDD
 */
export type ProposalResponseTransportationSummaryModelV1DepartureDate = string | null;

/**
 * Date of transport end, could be arrival at home or to an other stay. Ex: 20160117. Date format YYYYMMDD
 */
export type ProposalResponseTransportationSummaryModelV1ArrivalDate = string | null;

/**
 * Summary of transportation details such as city, date, and type of travel
 */
export interface ProposalResponseTransportationSummaryModelV1 {
  way: Way;
  /** transportation departure city */
  departure_city: string;
  /**  transportation final arrival city */
  arrival_city: string;
  transportation_type: TransportationType;
  cancellation_policy_type: CancellationPolicyTypeModel;
  /** indicates if clubmed transfer from the airport to the resort is included or not. */
  is_transfer_included: boolean;
  /** true if the transport has been purchased by ClubMed */
  clubmed_transport: boolean;
  /** Date of the first outward flight if transport, date of arrival in first stay if not, YYYYMMDD */
  departure_date: ProposalResponseTransportationSummaryModelV1DepartureDate;
  /** Date of transport end, could be arrival at home or to an other stay. Ex: 20160117. Date format YYYYMMDD */
  arrival_date: ProposalResponseTransportationSummaryModelV1ArrivalDate;
}

/**
 * list of transportation summaries
 */
export type ProposalTransportationSummaryModelV1 = ProposalResponseTransportationSummaryModelV1[];

export interface ProposalResponseVendorModel {
  /** Salesman id number */
  salesman_id?: string;
}

export type ProposalResponseModelV1BookingId = number | null;

/**
 * Locale with ISO 639-1 language and ISO 3166-1 country
 */
export type ProposalResponseModelV1Locale = string | null;

export interface ProposalResponseModelV1 {
  /**
   * Proposal identifier
   * @pattern ^\d+$
   */
  id: string;
  /** ClubMed Product identifier */
  product_id: string;
  booking_id?: ProposalResponseModelV1BookingId;
  /** a package_id from /products/{product_id}/packages resource */
  package_id: string;
  label: string;
  /** Resort arrival date. Ex: 20160117. Date format YYYYMMDD */
  resort_arrival_date: string;
  /** Resort departure date. Ex: 20160123. Date format YYYYMMDD */
  resort_departure_date: string;
  price?: ProposalPriceModelV1;
  /** Journey duration */
  duration?: number;
  alternative_price?: ProposalPriceModel;
  accommodations: AccommodationsModel;
  /**
   * count of remaining stock. Can be usefull for stress marketing
   * @minimum 0
   */
  remaining_stock: number;
  /** true if the associated booking can be created with OPTION status */
  option_available: boolean;
  option_durability?: ProposalOptionDurationModelV1;
  households?: ProposalHouseholdsModelV1;
  /** Locale with ISO 639-1 language and ISO 3166-1 country */
  locale: ProposalResponseModelV1Locale;
  _links?: LinksModel;
  transportation_summary?: ProposalTransportationSummaryModelV1;
  /** if true means that the proposal will exist during 6 months (15 days if false) */
  extend_persistence?: boolean;
  auto_optionable_status: AutoOptionableStatus;
  /** Indicates wether the proposal can be transformed into a booking or not. Always displayed as false when attendees are not added. */
  is_bookable: boolean;
  /** proposal creation date time */
  creation_date_time?: string;
  vendor?: ProposalResponseVendorModel;
}

/**
 * Defines the client's status at the time of the call
 */
export type CustomerStatus = 'NEW_CUSTOMER' | 'UNAVAILABLE' | 'PROSPECT' | 'CLIENT' | null;

export interface LegacyOptinModel {
  channel: ValidOptinChanelModel;
  /** True if the customer has agreed to be contacted on this channel */
  optin: boolean;
  /** True if the customer has agreed to be contacted by Club Med's partners, available only for EMAIL channel */
  optin_partners?: boolean;
}

export type LegacyOptinsModel = LegacyOptinModel[];

/**
 * What is paid : booking, upsale, option,...
 */
export type ActionCode = (typeof ActionCode)[keyof typeof ActionCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActionCode = {
  TOKENIZATION_CARD: 'TOKENIZATION_CARD',
  CALL_CENTER: 'CALL_CENTER',
  PAYMENT_BOOKING: 'PAYMENT_BOOKING',
  PAYMENT_OPTION: 'PAYMENT_OPTION',
  PAYMENT_SOLDE: 'PAYMENT_SOLDE',
  REFUND: 'REFUND',
  PAYMENT_UPGRADE_PACKAGE: 'PAYMENT_UPGRADE_PACKAGE',
  PAYMENT_UPGRADE_ACCOMODATION: 'PAYMENT_UPGRADE_ACCOMODATION',
  PAYMENT_UPGRADE_SERVICE: 'PAYMENT_UPGRADE_SERVICE',
  PAYMENT_SERVICES_IN_OPTION: 'PAYMENT_SERVICES_IN_OPTION',
  PAYMENT_PARTIAL: 'PAYMENT_PARTIAL',
} as const;

/**
 * Payment status
 */
export type StatutPaiement = (typeof StatutPaiement)[keyof typeof StatutPaiement];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatutPaiement = {
  CANCELED: 'CANCELED',
  CANCELLED: 'CANCELLED',
  PENDING: 'PENDING',
  REFUSED_CM: 'REFUSED_CM',
  OK: 'OK',
  REFUSED_PSP: 'REFUSED_PSP',
} as const;

/**
 * Payment description
 */
export interface Paiement {
  action_code?: ActionCode;
  /** Sales channel code */
  channel_code?: string;
  statutPaiement: StatutPaiement;
  /**
   * Payment Service Provider name with integration mode
   * @pattern ^[EM][0-9A-Z]+$
   */
  serveurId: string;
  /**
   * Payment amount, decimal separator is "."
   * @pattern ^[0-9]+[.][0-9]{2}$
   */
  montantVersement: string;
  /**
   * Payment currency, three letter ISO code
   * @pattern ^[A-Z]{3}$
   */
  codeDevise: string;
}

/**
 * File references
 */
export interface Dossier {
  /**
   * File number
   * @pattern ^[0-9]+$
   */
  numeroDossier: string;
  /**
   * Contract number
   * @pattern ^[0-9]+$
   */
  numeroContrat: string;
  /**
   * Client number
   * @pattern ^[0-9]+$
   */
  numeroClient: string;
}

/**
 * Error details if available.
 */
export type ErreurAnyOf = {
  /** Error code from module/Psp */
  returnCode?: string;
  /** Module/Psp name */
  moduleName?: string;
  /** Error message from module/Psp */
  errorMessage?: string;
};

/**
 * Error details if available.
 */
export type Erreur = ErreurAnyOf | null;

/**
 * Actual state of the payment
 */
export interface FinalisePaymentResponse {
  paiement: Paiement;
  dossier: Dossier;
  error?: Erreur;
}

/**
 * Model matching an xmResponse with a finalisePaymentResponse structure
 */
export interface PaymentStatusModel {
  finalisePaymentResponse: FinalisePaymentResponse;
  /** Should be null, for compatibility only */
  errors?: string;
}

export type StayAccommodationRoomsModel = RoomModel[];

/**
 * accommodation occupancy start date
 */
export type StayAccommodationModelStartDate = string | null;

/**
 * accommodation occupancy end date
 */
export type StayAccommodationModelEndDate = string | null;

/**
 * false if there is no baby bed in the room
 */
export type StayAccommodationModelBabyBed = boolean | null;

/**
 * Indicate if the room is sharable
 */
export type StayAccommodationModelSharedRoom = boolean | null;

/**
 * number of persons in the room
 */
export type StayAccommodationModelOccupation = 0 | null;

export interface StayAccommodationModel {
  /** accommodation occupancy start date */
  start_date?: StayAccommodationModelStartDate;
  /** accommodation occupancy end date */
  end_date?: StayAccommodationModelEndDate;
  /** number of accommodations for the id and time period */
  quantity: number;
  /** false if there is no baby bed in the room */
  baby_bed?: StayAccommodationModelBabyBed;
  /** Indicate if the room is sharable */
  shared_room?: StayAccommodationModelSharedRoom;
  /** number of persons in the room */
  occupation?: StayAccommodationModelOccupation;
  /** accommodation id */
  accommodation_id?: string;
  rooms?: StayAccommodationRoomsModel;
  _links?: LinksModel;
}

export type StayAccommodationsModel = StayAccommodationModel[];

/**
 * List of attendee
 */
export type BookingPackageAttendeeIdsModel = string[];

/**
 * package label
 */
export type BookingPackageModelLabel = string | null;

export interface BookingPackageModel {
  /** package id of the booking */
  id: string;
  /** package label */
  label?: BookingPackageModelLabel;
  attendee_ids?: BookingPackageAttendeeIdsModel;
  _links?: LinksModel;
}

export type BookingPackagesModel = BookingPackageModel[];

export interface AttendeePaymentScheduleModel {
  /** Payment schedule Id */
  id: string;
  /**
   * Customer ID (neolid clic)
   * @pattern ^[1-9][0-9]*$
   */
  customer_id?: string;
}

export type HouseholdPaymentScheduleModel = AttendeePaymentScheduleModel[];

/**
 * Due date for the payment
 */
export type DepositRepaymentScheduleModelV1Deadline = string | null;

export interface DepositRepaymentScheduleModelV1 {
  /**
   * Amount to pay for this repayment
   * @minimum 0
   */
  expected_payment_amount?: number;
  /** Due date for the payment */
  deadline: DepositRepaymentScheduleModelV1Deadline;
}

/**
 * List of repayment deposit
 */
export type DepositRepaymentScheduleModelListV1 = DepositRepaymentScheduleModelV1[];

export interface HouseholdPaymentScheduleModelV1 {
  attendees?: HouseholdPaymentScheduleModel;
  /** @minimum 0 */
  total: number;
  deposit_repayment_schedule?: DepositRepaymentScheduleModelListV1;
}

export type HouseholdPaymentScheduleModels = HouseholdPaymentScheduleModelV1[];

export interface ProposalPaymentScheduleModelV1 {
  /**
   * The iso 3 currency. Ex: CNY,EUR,..
   * @minLength 3
   * @maxLength 3
   */
  currency: string;
  /** Show if the agency's commission is included or not */
  commission_included: boolean;
  households?: HouseholdPaymentScheduleModels;
}

/**
 * Customer loyalty program status (not editable)
 */
export type CustomerLoyaltyProgramStatusV2Model =
  (typeof CustomerLoyaltyProgramStatusV2Model)[keyof typeof CustomerLoyaltyProgramStatusV2Model];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerLoyaltyProgramStatusV2Model = {
  NONE: 'NONE',
  TURQUOISE: 'TURQUOISE',
  SILVER: 'SILVER',
  GOLD: 'GOLD',
  PLATINUM: 'PLATINUM',
  UNAVAILABLE_FOR_THIS_COUNTRY: 'UNAVAILABLE_FOR_THIS_COUNTRY',
  EXCLUDED: 'EXCLUDED',
  UNAVAILABLE: 'UNAVAILABLE',
} as const;

/**
 * Indicates the status of the GM before the overhaul of the loyalty program (not editable)
 */
export type CustomerLoyaltyProgramPreviousStatusModel =
  (typeof CustomerLoyaltyProgramPreviousStatusModel)[keyof typeof CustomerLoyaltyProgramPreviousStatusModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerLoyaltyProgramPreviousStatusModel = {
  NONE: 'NONE',
  TURQUOISE: 'TURQUOISE',
  SILVER: 'SILVER',
  GOLD: 'GOLD',
  PLATINUM: 'PLATINUM',
  UNAVAILABLE_FOR_THIS_COUNTRY: 'UNAVAILABLE_FOR_THIS_COUNTRY',
  EXCLUDED: 'EXCLUDED',
  UNAVAILABLE: 'UNAVAILABLE',
} as const;

/**
 * Number of points accumulated (not editable)
 */
export type CustomerLoyaltyProgramV2ModelAnyOfPoints = number | null;

/**
 * (not editable)
 */
export type CustomerLoyaltyProgramV2ModelAnyOf = {
  status?: CustomerLoyaltyProgramStatusV2Model;
  /** Indicates if this GM is platinum for life when he has reached platinum status for a certain number of years in a row */
  is_platinum_for_life?: boolean;
  /** Year when Platinum for Life status was granted */
  platinum_for_life_since?: string;
  /** Number of points accumulated (not editable) */
  points?: CustomerLoyaltyProgramV2ModelAnyOfPoints;
  previous_status?: CustomerLoyaltyProgramPreviousStatusModel;
};

/**
 * (not editable)
 */
export type CustomerLoyaltyProgramV2Model = CustomerLoyaltyProgramV2ModelAnyOf | null;

/**
 * location number
 * @maxLength 50
 */
export type ProfileAddressModelAnyOfNumber = string | null;

/**
 * location street
 * @maxLength 100
 */
export type ProfileAddressModelAnyOfStreet = string | null;

/**
 * additional information (eg: floor number)
 * @maxLength 50
 */
export type ProfileAddressModelAnyOfAddOn = string | null;

/**
 * Locality name (might not be applicable for every country)
 * @maxLength 100
 */
export type ProfileAddressModelAnyOfTown = string | null;

/**
 * city name
 * @maxLength 150
 */
export type ProfileAddressModelAnyOfCity = string | null;

/**
 * postal code
 * @maxLength 50
 */
export type ProfileAddressModelAnyOfZipCode = string | null;

/**
 * administrative division
 * @maxLength 100
 */
export type ProfileAddressModelAnyOfStateOrDistrict = string | null;

/**
 * Country
 * @maxLength 100
 */
export type ProfileAddressModelAnyOfCountry = string | null;

/**
 * ISO 3166-1 alpha-2 country code
 * @maxLength 3
 */
export type ProfileAddressModelAnyOfCountryCode = string | null;

/**
 * additional information such as one's host or building
 * @maxLength 100
 */
export type ProfileAddressModelAnyOfAdditionalInformation1 = string | null;

/**
 * additional information such as one's host or building
 * @maxLength 100
 */
export type ProfileAddressModelAnyOfAdditionalInformation2 = string | null;

export type ProfileAddressModelAnyOf = {
  /**
   * location number
   * @maxLength 50
   */
  number?: ProfileAddressModelAnyOfNumber;
  /**
   * location street
   * @maxLength 100
   */
  street?: ProfileAddressModelAnyOfStreet;
  /**
   * additional information (eg: floor number)
   * @maxLength 50
   */
  add_on?: ProfileAddressModelAnyOfAddOn;
  /**
   * Locality name (might not be applicable for every country)
   * @maxLength 100
   */
  town?: ProfileAddressModelAnyOfTown;
  /**
   * city name
   * @maxLength 150
   */
  city?: ProfileAddressModelAnyOfCity;
  /**
   * postal code
   * @maxLength 50
   */
  zip_code?: ProfileAddressModelAnyOfZipCode;
  /**
   * administrative division
   * @maxLength 100
   */
  state_or_district?: ProfileAddressModelAnyOfStateOrDistrict;
  /**
   * Country
   * @maxLength 100
   */
  country?: ProfileAddressModelAnyOfCountry;
  /**
   * ISO 3166-1 alpha-2 country code
   * @maxLength 3
   */
  country_code?: ProfileAddressModelAnyOfCountryCode;
  /**
   * additional information such as one's host or building
   * @maxLength 100
   */
  additional_information_1?: ProfileAddressModelAnyOfAdditionalInformation1;
  /**
   * additional information such as one's host or building
   * @maxLength 100
   */
  additional_information_2?: ProfileAddressModelAnyOfAdditionalInformation2;
};

export type ProfileAddressModel = ProfileAddressModelAnyOf | null;

/**
 * Links
 */
export type NullableLinksModel = LinkModel[] | null;

/**
 * email
 */
export type ProfileModelV2Email = string | null;

/**
 * great member number (not editable)
 */
export type ProfileModelV2GmNumber = string | null;

/**
 * great member gender
 */
export type ProfileModelV2Gender = string | null;

/**
 * civility
 */
export type ProfileModelV2Civility = string | null;

/**
 * civility (unicode version)
 */
export type ProfileModelV2UnicodeCivility = string | null;

/**
 * first name
 */
export type ProfileModelV2FirstName = string | null;

/**
 * first name (unicode version)
 */
export type ProfileModelV2UnicodeFirstName = string | null;

/**
 * second name
 */
export type ProfileModelV2SecondName = string | null;

/**
 * seconde name (unicode version)
 */
export type ProfileModelV2UnicodeSecondName = string | null;

/**
 * third name
 */
export type ProfileModelV2ThirdName = string | null;

/**
 * third name (unicode version)
 */
export type ProfileModelV2UnicodeThirdName = string | null;

/**
 * fourth name
 */
export type ProfileModelV2FourthName = string | null;

/**
 * fourth name (unicode version)
 */
export type ProfileModelV2UnicodeFourthName = string | null;

/**
 * last name
 */
export type ProfileModelV2LastName = string | null;

/**
 * last name (unicode version)
 */
export type ProfileModelV2UnicodeLastName = string | null;

/**
 * Sanitary pass number
 */
export type ProfileModelV2HealthPassId = string | null;

/**
 * Defines the status of the CLIENT in the database. CLIENT OR PROSPECT (not editable)
 */
export type ProfileModelV2CustomerType = string | null;

/**
 * date of birth is DEPRECATED, use birthdate instead
 */
export type ProfileModelV2Birthday = string | null;

/**
 * date of birth
 */
export type ProfileModelV2Birthdate = string | null;

/**
 * ISO 2 country code
 */
export type ProfileModelV2BirthCountryCode = string | null;

/**
 * customer birth city
 */
export type ProfileModelV2BirthCity = string | null;

/**
 * customer language. ISO 2 code
 */
export type ProfileModelV2LanguageCode = string | null;

/**
 * Indicates if a client is blacklisted or not
 */
export type ProfileModelV2Blacklisted = boolean | null;

/**
 * Indicates the filiation number of a customer
 */
export type ProfileModelV2FiliationNumber = string | null;

/**
 * Locale with ISO 639-1 language and ISO 3166-1 country
 */
export type ProfileModelV2Locale = string | null;

export interface ProfileModelV2 {
  /** email */
  email?: ProfileModelV2Email;
  /** great member number (not editable) */
  gm_number?: ProfileModelV2GmNumber;
  /** great member gender */
  gender?: ProfileModelV2Gender;
  /** civility */
  civility?: ProfileModelV2Civility;
  /** civility (unicode version) */
  unicode_civility?: ProfileModelV2UnicodeCivility;
  /** first name */
  first_name?: ProfileModelV2FirstName;
  /** first name (unicode version) */
  unicode_first_name?: ProfileModelV2UnicodeFirstName;
  /** second name */
  second_name?: ProfileModelV2SecondName;
  /** seconde name (unicode version) */
  unicode_second_name?: ProfileModelV2UnicodeSecondName;
  /** third name */
  third_name?: ProfileModelV2ThirdName;
  /** third name (unicode version) */
  unicode_third_name?: ProfileModelV2UnicodeThirdName;
  /** fourth name */
  fourth_name?: ProfileModelV2FourthName;
  /** fourth name (unicode version) */
  unicode_fourth_name?: ProfileModelV2UnicodeFourthName;
  /** last name */
  last_name?: ProfileModelV2LastName;
  /** last name (unicode version) */
  unicode_last_name?: ProfileModelV2UnicodeLastName;
  /** Sanitary pass number */
  health_pass_id?: ProfileModelV2HealthPassId;
  /** Defines the status of the CLIENT in the database. CLIENT OR PROSPECT (not editable) */
  customer_type?: ProfileModelV2CustomerType;
  customer_status?: CustomerStatus;
  /** date of birth is DEPRECATED, use birthdate instead */
  birthday?: ProfileModelV2Birthday;
  /** date of birth */
  birthdate?: ProfileModelV2Birthdate;
  /** ISO 2 country code */
  birth_country_code?: ProfileModelV2BirthCountryCode;
  /** customer birth city */
  birth_city?: ProfileModelV2BirthCity;
  /** customer language. ISO 2 code */
  language_code?: ProfileModelV2LanguageCode;
  phones?: PhonesModel;
  loyalty_program?: CustomerLoyaltyProgramV2Model;
  address?: ProfileAddressModel;
  optins?: LegacyOptinsModel;
  /** true if the customer allows the use of its personal data by Club Med */
  personal_data_usage_allowed: boolean;
  /** Indicates if a client is blacklisted or not */
  blacklisted?: ProfileModelV2Blacklisted;
  /** Indicates the filiation number of a customer */
  filiation_number?: ProfileModelV2FiliationNumber;
  identity: NationalIdentifierCodeModel;
  /** Locale with ISO 639-1 language and ISO 3166-1 country */
  locale?: ProfileModelV2Locale;
  _links?: NullableLinksModel;
}

/**
 * Indicates if the expiration date is reliable or not. An expiration date is not reliable when the transport is included since it can be cancelled by the transport supplier. The expiration date of a booking without transport is considered as reliable.
 */
export type OptionDurabilityAnyOfIsReliable = boolean | null;

export type OptionDurabilityAnyOf = {
  /** Indicates if the expiration date is reliable or not. An expiration date is not reliable when the transport is included since it can be cancelled by the transport supplier. The expiration date of a booking without transport is considered as reliable. */
  is_reliable?: OptionDurabilityAnyOfIsReliable;
  /** Booking expiration date and time */
  expiration_date_time?: string;
};

export type OptionDurability = OptionDurabilityAnyOf | null;

/**
 * Indicates if this option has been renewed or not
 */
export type CustomerBookingRenewalModelAnyOfHasBeenRenewed = boolean | null;

/**
 * Indicates if this booking or option has been created by option renewal process
 */
export type CustomerBookingRenewalModelAnyOfIsFromRenewal = boolean | null;

export type CustomerBookingRenewalModelAnyOf = {
  /** Indicates if this option has been renewed or not */
  has_been_renewed?: CustomerBookingRenewalModelAnyOfHasBeenRenewed;
  /** Indicates if this booking or option has been created by option renewal process */
  is_from_renewal?: CustomerBookingRenewalModelAnyOfIsFromRenewal;
};

export type CustomerBookingRenewalModel = CustomerBookingRenewalModelAnyOf | null;

/**
 * booking payment's status
 */
export type CustomerBookingPaymentStatusModel =
  (typeof CustomerBookingPaymentStatusModel)[keyof typeof CustomerBookingPaymentStatusModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerBookingPaymentStatusModel = {
  PAID: 'PAID',
  UNPAID: 'UNPAID',
  IN_CREDIT: 'IN_CREDIT',
  PENDING: 'PENDING',
  UNKNOWN: 'UNKNOWN',
} as const;

export type TotalPriceAnyOf = {
  /** Indicates the total price of the booking */
  amount: number;
  /**
   * The iso 3 currency. Ex: CNY,EUR,..
   * @minLength 3
   * @maxLength 3
   */
  currency: string;
};

export type TotalPrice = TotalPriceAnyOf | null;

export type StayAttendeeIdsModel = string[];

/**
 * adult attendees number
 */
export type BookingStayAttendeeAdultsCount =
  (typeof BookingStayAttendeeAdultsCount)[keyof typeof BookingStayAttendeeAdultsCount];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BookingStayAttendeeAdultsCount = {
  NUMBER_0: 0,
} as const;

/**
 * children attendees number
 */
export type BookingStayAttendeeChildrenCount =
  (typeof BookingStayAttendeeChildrenCount)[keyof typeof BookingStayAttendeeChildrenCount];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BookingStayAttendeeChildrenCount = {
  NUMBER_0: 0,
} as const;

/**
 * arrival date for this group of attendees YYYYMMDD
 */
export type BookingStayAttendeeStartDate = string | null;

/**
 * leaving date for this group of attendees YYYYMMDD
 */
export type BookingStayAttendeeEndDate = string | null;

export interface BookingStayAttendee {
  /** adult attendees number */
  adults_count?: BookingStayAttendeeAdultsCount;
  /** children attendees number */
  children_count?: BookingStayAttendeeChildrenCount;
  _links?: LinksModel;
  /** arrival date for this group of attendees YYYYMMDD */
  start_date?: BookingStayAttendeeStartDate;
  /** leaving date for this group of attendees YYYYMMDD */
  end_date?: BookingStayAttendeeEndDate;
  attendee_ids?: StayAttendeeIdsModel;
}

export type BookingStayAttendees = BookingStayAttendee[];

/**
 * Transportation mode
 */
export type CustomerBookingStayOutwardTripTransportationModeModelV2 =
  (typeof CustomerBookingStayOutwardTripTransportationModeModelV2)[keyof typeof CustomerBookingStayOutwardTripTransportationModeModelV2];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerBookingStayOutwardTripTransportationModeModelV2 = {
  PLANE: 'PLANE',
  TRAIN: 'TRAIN',
  BOAT: 'BOAT',
  UNKNOWN: 'UNKNOWN',
} as const;

export type TransportationsOutwardTrip = CustomerBookingStayOutwardTripTransportationModeModelV2[];

/**
 * city of departure
 */
export type OutwardTripModelV2AnyOfDepartureCity = string | null;

/**
 * city of arrival
 */
export type OutwardTripModelV2AnyOfArrivalCity = string | null;

export type OutwardTripModelV2AnyOf = {
  /** city of departure */
  departure_city?: OutwardTripModelV2AnyOfDepartureCity;
  /** city of arrival */
  arrival_city?: OutwardTripModelV2AnyOfArrivalCity;
  transportation?: TransportationsOutwardTrip;
};

export type OutwardTripModelV2 = OutwardTripModelV2AnyOf | null;

/**
 * resort arrival date which can be different from the departure_date, if the flight lasts more than 1 day for example YYYYMMDD
 */
export type CustomerBookingStayModelV2ResortArrivalDate = string | null;

/**
 * resort leaving date, YYYYMMDD
 */
export type CustomerBookingStayModelV2ResortLeavingDate = string | null;

/**
 * Total number of adults for the stay
 */
export type CustomerBookingStayModelV2TotalAdultsCount =
  (typeof CustomerBookingStayModelV2TotalAdultsCount)[keyof typeof CustomerBookingStayModelV2TotalAdultsCount];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerBookingStayModelV2TotalAdultsCount = {
  NUMBER_0: 0,
} as const;

/**
 * Total number of children for the stay
 */
export type CustomerBookingStayModelV2TotalChildrenCount =
  (typeof CustomerBookingStayModelV2TotalChildrenCount)[keyof typeof CustomerBookingStayModelV2TotalChildrenCount];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerBookingStayModelV2TotalChildrenCount = {
  NUMBER_0: 0,
} as const;

/**
 * false if no upsell can be applied to this booking using the api
 */
export type CustomerBookingStayModelV2ApiUpsellAvailable = boolean | null;

export interface CustomerBookingStayModelV2 {
  /** stay id */
  id?: string;
  /** product concerned by the booking */
  product_id?: string;
  /** Label (name of product) */
  label?: string;
  product_type?: ProductTypeModel;
  /** resort arrival date which can be different from the departure_date, if the flight lasts more than 1 day for example YYYYMMDD */
  resort_arrival_date?: CustomerBookingStayModelV2ResortArrivalDate;
  /** resort leaving date, YYYYMMDD */
  resort_leaving_date?: CustomerBookingStayModelV2ResortLeavingDate;
  /** duration of the stay */
  duration?: number;
  attendees?: BookingStayAttendees;
  /** Total number of adults for the stay */
  total_adults_count?: CustomerBookingStayModelV2TotalAdultsCount;
  /** Total number of children for the stay */
  total_children_count?: CustomerBookingStayModelV2TotalChildrenCount;
  outward_trip?: OutwardTripModelV2;
  /** false if no upsell can be applied to this booking using the api */
  api_upsell_available: CustomerBookingStayModelV2ApiUpsellAvailable;
  accommodations?: StayAccommodationsModel;
  packages?: BookingPackagesModel;
  _links?: LinksModel;
}

/**
 * list of stays
 */
export type CustomerBookingStaysModelV2 = CustomerBookingStayModelV2[];

/**
 * Date of event
 */
export type CustomerBookingEventModelDate = string | null;

export interface CustomerBookingEventModel {
  /** Code of event */
  code: string;
  /** Type of event */
  label: string;
  /** Date of event */
  date: CustomerBookingEventModelDate;
}

/**
 * Events
 */
export type CustomerBookingEventsModel = CustomerBookingEventModel[];

/**
 * booking creation date, YYYYMMDD
 */
export type CustomerBookingModelV3CreationDate = string | null;

/**
 * booking return date: date of last return flight if transport, date of departure of last stay if not. YYYYMMDD
 */
export type CustomerBookingModelV3ReturnDate = string | null;

/**
 * true if the booking is composed of mulitple sales contracts, owned by different customers. Online sale processes are not possible in this case.
 */
export type CustomerBookingModelV3MultipleSaleContracts = boolean | null;

/**
 * Deprecated - Indicates if an option has been renewed or not
 */
export type CustomerBookingModelV3IsRenewedOption = boolean | null;

/**
 * defines if GM's payment is allowed for an agency
 */
export type CustomerBookingModelV3AllowedToPay = boolean | null;

/**
 * Language/Country the booking has been created with
 */
export type CustomerBookingModelV3Locale = string | null;

export interface CustomerBookingModelV3 {
  /** booking id */
  id: string;
  /** booking creation date, YYYYMMDD */
  creation_date?: CustomerBookingModelV3CreationDate;
  /** booking departure date: date of first outward flight if transport, date of arrival in first stay if not. YYYYMMDD */
  departure_date?: string;
  /** booking return date: date of last return flight if transport, date of departure of last stay if not. YYYYMMDD */
  return_date?: CustomerBookingModelV3ReturnDate;
  /** true if the booking is composed of mulitple sales contracts, owned by different customers. Online sale processes are not possible in this case. */
  multiple_sale_contracts: CustomerBookingModelV3MultipleSaleContracts;
  option_durability?: OptionDurability;
  booking_status?: BookingStatus;
  /** Deprecated - Indicates if an option has been renewed or not */
  is_renewed_option?: CustomerBookingModelV3IsRenewedOption;
  booking_renewal?: CustomerBookingRenewalModel;
  payment_status?: CustomerBookingPaymentStatusModel;
  /** defines if GM's payment is allowed for an agency */
  allowed_to_pay?: CustomerBookingModelV3AllowedToPay;
  total_price?: TotalPrice;
  discounts?: DiscountsModelV3;
  /** Language/Country the booking has been created with */
  locale?: CustomerBookingModelV3Locale;
  vendor?: VendorModel;
  stays?: CustomerBookingStaysModelV2;
  events: CustomerBookingEventsModel;
  _links?: LinksModel;
}

export interface CustomerBookingPaymentSchedule {
  /** amount to pay before the deadline */
  amount?: number;
  /** deadline for payment of the amount */
  deadline?: string;
}

export type PaymentSchedules = CustomerBookingPaymentSchedule[];

/**
 * Payment schedule of a booking
 */
export interface CustomerBookingPaymentScheduleModel {
  /**
   * The iso 3 currency. Ex: CNY,EUR,..
   * @minLength 3
   * @maxLength 3
   */
  currency: string;
  /** amount already paid */
  paid?: number;
  /** total amount to pay */
  total?: number;
  payment_schedules?: PaymentSchedules;
}

export type CartUpgradeRoomPriceModelAnyOf = {
  /** Room price amount */
  amount: number;
  /** Price currency */
  currency: string;
};

export type CartUpgradeRoomPriceModel = CartUpgradeRoomPriceModelAnyOf | null;

export interface CartUpgradeRoomAttendeeModel {
  /** Attendee id in this booking */
  id: string;
  /** Attendee type [MAIN, KID, ADULT] */
  type: string;
  /** Attendee birthdate (YYYYMMDD) */
  birthdate?: string;
}

/**
 * List of the attendees
 * @minItems 1
 */
export type CartUpgradeRoomAttendeesModel = CartUpgradeRoomAttendeeModel[];

export interface CartUpgradeRoomAccommodationModel {
  /** Id of the accommodation */
  id: string;
  attendees: CartUpgradeRoomAttendeesModel;
  /** Number of accommodations where the attendees will be allocated */
  quantity: number;
  /** Number of occupants in the accommodation */
  occupancy: number;
}

export type CartUpgradeRoomAccommodationsModel = CartUpgradeRoomAccommodationModel[];

export interface CartUpgradeRoomModel {
  price?: CartUpgradeRoomPriceModel;
  accommodations?: CartUpgradeRoomAccommodationsModel;
}

export interface PaymentScheduleDeadlineItemModel {
  /** amount */
  amount?: number;
  /** Payment Deadline date */
  deadline: string;
}

export type PaymentScheduleDeadlineItemsModel = PaymentScheduleDeadlineItemModel[];

/**
 * The iso 3 currency. Ex: CNY,EUR,..
 * @minLength 3
 * @maxLength 3
 */
export type PaymentScheduleModelCurrency = string | null;

/**
 * paid
 */
export type PaymentScheduleModelPaid = number | null;

/**
 * paid
 */
export type PaymentScheduleModelTotal = number | null;

export interface PaymentScheduleModel {
  /**
   * The iso 3 currency. Ex: CNY,EUR,..
   * @minLength 3
   * @maxLength 3
   */
  currency: PaymentScheduleModelCurrency;
  /** paid */
  paid?: PaymentScheduleModelPaid;
  /** paid */
  total?: PaymentScheduleModelTotal;
  payment_schedules?: PaymentScheduleDeadlineItemsModel;
}

/**
 * Payment reason
 */
export type Action = (typeof Action)[keyof typeof Action];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Action = {
  PAYMENT_CART: 'PAYMENT_CART',
  PAYMENT_RESA: 'PAYMENT_RESA',
  PAYMENT_OPTION: 'PAYMENT_OPTION',
  PAYMENT_SOLDE: 'PAYMENT_SOLDE',
  PAYMENT_PARTIAL: 'PAYMENT_PARTIAL',
  PAYMENT_UPGRADE_ROOM: 'PAYMENT_UPGRADE_ROOM',
  PAYMENT_SERVICES_IN_OPTION: 'PAYMENT_SERVICES_IN_OPTION',
} as const;

/**
 * Sales network id returned by the /partners/{partner_id}/sales_networks resources. Ex: OPERA_00_P2T
 */
export type PaymentOrderModelSalesNetworkId = string | null;

/**
 * amount for a donation to Club Med's charity foundation
 */
export type PaymentOrderModelDonationAmount = 0 | null;

export interface PaymentOrderModel {
  /**
   * Customer ID (neolid clic)
   * @pattern ^[1-9][0-9]*$
   */
  customer_id: string;
  /**
   * booking Id (file number)
   * @pattern ^\d+$
   */
  booking_id: string;
  /** Sales network id returned by the /partners/{partner_id}/sales_networks resources. Ex: OPERA_00_P2T */
  sales_network_id?: PaymentOrderModelSalesNetworkId;
  /** Provider id */
  provider_id: string;
  /**
   * The iso 3 currency. Ex: CNY,EUR,..
   * @minLength 3
   * @maxLength 3
   */
  currency?: string;
  /** Payment amount */
  amount: number;
  /** amount for a donation to Club Med's charity foundation */
  donation_amount?: PaymentOrderModelDonationAmount;
  action: Action;
}

export interface PaymentIdModel {
  /**
   * Payment id
   * @pattern ^[0-9a-zA-Z]+([-_][0-9a-zA-Z]+)*$
   */
  id: string;
}

/**
 * Booking status. If not provided, the booking status will be PENDING_PAYMENT for GM
 */
export type CreateBookingRequestBookingStatusModel =
  (typeof CreateBookingRequestBookingStatusModel)[keyof typeof CreateBookingRequestBookingStatusModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateBookingRequestBookingStatusModel = {
  OPTION: 'OPTION',
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  VALIDATED: 'VALIDATED',
} as const;

/**
 * Attendee type
 */
export type CreateBookingResponseTypesModel =
  (typeof CreateBookingResponseTypesModel)[keyof typeof CreateBookingResponseTypesModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateBookingResponseTypesModel = {
  MAIN: 'MAIN',
  ADULT: 'ADULT',
  KID: 'KID',
} as const;

export interface CreateBookingResponseAttendeeModel {
  /** Attendee customer identifier */
  customer_id: number;
  type: CreateBookingResponseTypesModel;
}

/**
 * location number
 * @maxLength 50
 */
export type ProposalHouseholdAddressV1ModelAnyOfNumber = string | null;

/**
 * location street
 * @maxLength 100
 */
export type ProposalHouseholdAddressV1ModelAnyOfStreet = string | null;

/**
 * additional information (eg: floor number)
 * @maxLength 50
 */
export type ProposalHouseholdAddressV1ModelAnyOfAddOn = string | null;

/**
 * Locality name (might not be applicable for every country)
 * @maxLength 100
 */
export type ProposalHouseholdAddressV1ModelAnyOfTown = string | null;

/**
 * city name
 * @maxLength 150
 */
export type ProposalHouseholdAddressV1ModelAnyOfCity = string | null;

/**
 * postal code
 * @maxLength 50
 */
export type ProposalHouseholdAddressV1ModelAnyOfZipCode = string | null;

/**
 * administrative division
 * @maxLength 100
 */
export type ProposalHouseholdAddressV1ModelAnyOfStateOrDistrict = string | null;

/**
 * Country
 * @maxLength 100
 */
export type ProposalHouseholdAddressV1ModelAnyOfCountry = string | null;

/**
 * ISO 3166-1 alpha-2 country code
 * @maxLength 3
 */
export type ProposalHouseholdAddressV1ModelAnyOfCountryCode = string | null;

/**
 * additional information such as one's host or building
 * @maxLength 100
 */
export type ProposalHouseholdAddressV1ModelAnyOfAdditionalInformation1 = string | null;

/**
 * additional information such as one's host or building
 * @maxLength 100
 */
export type ProposalHouseholdAddressV1ModelAnyOfAdditionalInformation2 = string | null;

export type ProposalHouseholdAddressV1ModelAnyOf = {
  /**
   * location number
   * @maxLength 50
   */
  number?: ProposalHouseholdAddressV1ModelAnyOfNumber;
  /**
   * location street
   * @maxLength 100
   */
  street?: ProposalHouseholdAddressV1ModelAnyOfStreet;
  /**
   * additional information (eg: floor number)
   * @maxLength 50
   */
  add_on?: ProposalHouseholdAddressV1ModelAnyOfAddOn;
  /**
   * Locality name (might not be applicable for every country)
   * @maxLength 100
   */
  town?: ProposalHouseholdAddressV1ModelAnyOfTown;
  /**
   * city name
   * @maxLength 150
   */
  city?: ProposalHouseholdAddressV1ModelAnyOfCity;
  /**
   * postal code
   * @maxLength 50
   */
  zip_code?: ProposalHouseholdAddressV1ModelAnyOfZipCode;
  /**
   * administrative division
   * @maxLength 100
   */
  state_or_district?: ProposalHouseholdAddressV1ModelAnyOfStateOrDistrict;
  /**
   * Country
   * @maxLength 100
   */
  country?: ProposalHouseholdAddressV1ModelAnyOfCountry;
  /**
   * ISO 3166-1 alpha-2 country code
   * @maxLength 3
   */
  country_code?: ProposalHouseholdAddressV1ModelAnyOfCountryCode;
  /**
   * additional information such as one's host or building
   * @maxLength 100
   */
  additional_information_1?: ProposalHouseholdAddressV1ModelAnyOfAdditionalInformation1;
  /**
   * additional information such as one's host or building
   * @maxLength 100
   */
  additional_information_2?: ProposalHouseholdAddressV1ModelAnyOfAdditionalInformation2;
};

export type ProposalHouseholdAddressV1Model = ProposalHouseholdAddressV1ModelAnyOf | null;

export interface ProposalAttendeeInputTravelDocumentV2Model {
  document_number?: string;
  type?: string;
  /** customer passport expiration date (YYYYMMDD format) */
  expiration_date?: string;
  /** customer passport issuing date (YYYYMMDD format) */
  issuing_date?: string;
  /** customer passport nationality (ISO2 country code) */
  nationality?: string;
  /** customer document issuing country (ISO2 country code) */
  issuing_country?: string;
  /** customer birth country (ISO2 country code) */
  birth_country?: string;
  /** describes the issuing entity of the document */
  authority?: string;
}

export type ProposalAttendeeInputTravelDocumentsModel =
  ProposalAttendeeInputTravelDocumentV2Model[];

export interface ProposalAttendeeInputOptin {
  channel: ValidOptinChanelModel;
  /** True if the customer has agreed to be contacted on this channel */
  optin: boolean;
  /** True if the customer has agreed to be contacted by Club Med's partners, available only for EMAIL channel */
  optin_partners?: boolean;
}

/**
 * optin array
 */
export type ProposalAttendeeInputOptinsV1 = ProposalAttendeeInputOptin[];

export interface ProposalAttendeeInputV2Model {
  id: string;
  /**
   * Customer ID (neolid clic)
   * @pattern ^[1-9][0-9]*$
   */
  customer_id?: string;
  first_name?: string;
  unicode_first_name?: string;
  last_name?: string;
  unicode_last_name?: string;
  email?: string;
  civility_code?: string;
  /** Health pass id */
  health_pass_id?: string;
  identity?: NationalIdentifierCodeModel;
  /**  
Supported formats: `YYYY-MM-DD`, `YYYYMMDD`, `YYYYMM` */
  birthdate?: string;
  travel_documents?: ProposalAttendeeInputTravelDocumentsModel;
  phones?: PhonesModel;
  optins?: ProposalAttendeeInputOptinsV1;
}

export type ProposalAttendeesInputV1Model = ProposalAttendeeInputV2Model[];

/**
 * customer language. ISO 2 code
 */
export type ProposalHouseholdV1ModelLanguageCode = string | null;

export interface ProposalHouseholdV1Model {
  /** The id of the household to which the attendees belong */
  household_id: string;
  address?: ProposalHouseholdAddressV1Model;
  attendees?: ProposalAttendeesInputV1Model;
  /** customer language. ISO 2 code */
  language_code?: ProposalHouseholdV1ModelLanguageCode;
}

export type PutProposalAttendeesV1PayloadModel = ProposalHouseholdV1Model[];

export interface CreateBookingRequestPriceModel {
  /** Price requested by the user in his registered currency. Will retrieve a proposal if the price is related to an offer. */
  requested_price: number;
}

/**
 * Arrival date in the resort (it is not the journey departure date. Date format YYYYMMDD)
 */
export type CreateDirectBookingRequestModelResortArrivalDate = string | null;

/**
 * Package id from /products/{id}/packages
 */
export type CreateDirectBookingRequestModelPackageId = string | null;

/**
 * Code allowing to add a voucher to the requested proposal
 */
export type CreateDirectBookingRequestModelVoucherCode = string | null;

/**
 * Sales network id returned by the /partners/{partner_id}/sales_networks resources. Ex: OPERA_00_P2T
 */
export type CreateDirectBookingRequestModelSalesNetworkId = string | null;

/**
 * Email of the seller recorded in the booking
 */
export type CreateDirectBookingRequestModelSellerEmail = string | null;

/**
 * Salesman id number
 */
export type CreateDirectBookingRequestModelSalesmanId = string | null;

/**
 * Comment to be sent to Club Med's tools
 */
export type CreateDirectBookingRequestModelComment = string | null;

export interface CreateDirectBookingRequestModel {
  /** Arrival date in the resort (it is not the journey departure date. Date format YYYYMMDD) */
  resort_arrival_date: CreateDirectBookingRequestModelResortArrivalDate;
  /** Number of nights into the resort. */
  duration: number;
  /** Product id. Ex: SAYC */
  product_id: string;
  /** Package id from /products/{id}/packages */
  package_id?: CreateDirectBookingRequestModelPackageId;
  /** Code allowing to add a voucher to the requested proposal */
  voucher_code?: CreateDirectBookingRequestModelVoucherCode;
  /** Sales network id returned by the /partners/{partner_id}/sales_networks resources. Ex: OPERA_00_P2T */
  sales_network_id?: CreateDirectBookingRequestModelSalesNetworkId;
  /** Transfer code from products/{id}/transfers resource. Ex: SAYVSY */
  transfer_code?: string;
  /** The departure option id from product/id, booking criteria section. Ex: PAR. If it is PAR, get proposals with transportation */
  departure_option_id?: string;
  /** Accommodation id */
  accommodation_id?: string;
  households?: PutProposalAttendeesV1PayloadModel;
  /** Identifier referencing the associated business opportunity in Club Med CRM, linking the call or lead to a potential booking for tracking and conversion. */
  opportunity_id?: string;
  /** Allows the sending of the e-mail summarizing the booking information */
  sending_option_information?: boolean;
  booking_status?: CreateBookingRequestBookingStatusModel;
  /** Email of the seller recorded in the booking */
  seller_email?: CreateDirectBookingRequestModelSellerEmail;
  /** Salesman id number */
  salesman_id?: CreateDirectBookingRequestModelSalesmanId;
  /** Comment to be sent to Club Med's tools */
  comment?: CreateDirectBookingRequestModelComment;
  /**
   * Deprecated - Indicates the expired option booking ID that might be renewed.
   * @pattern ^\d+$
   */
  expired_option_booking_id_for_renewal?: string;
  /**
   * Proposal identifier
   * @pattern ^\d+$
   */
  proposal_id?: string;
  price?: CreateBookingRequestPriceModel;
}

/**
 * Household's attendees
 */
export type CreateBookingAttendeesModel = CreateBookingResponseAttendeeModel[];

export interface CreateBookingHouseholdModel {
  attendees?: CreateBookingAttendeesModel;
}

/**
 * Booking households
 */
export type CreateBookingHouseholdsModel = CreateBookingHouseholdModel[];

export type BookingOptionDurabilityAnyOf = {
  /** Indicates if the expiration date is reliable or not. An expiration date is not reliable when the transport is included since it can be cancelled by the transport supplier. The expiration date of a booking without transport is considered as reliable. */
  is_reliable: boolean;
  /** Booking expiration date and time */
  expiration_date_time: string;
};

export type BookingOptionDurability = BookingOptionDurabilityAnyOf | null;

export interface CreateBookingResponseModel {
  /** Booking identifier */
  booking_id: string;
  households: CreateBookingHouseholdsModel;
  option_durability: BookingOptionDurability;
}

/**
 * payment redirect headers
 */
export type HeadersModelAnyOf = {
  /** Content type */
  'Content-type'?: string;
};

/**
 * payment redirect headers
 */
export type HeadersModel = HeadersModelAnyOf | null;

/**
 * device type
 */
export type Device = (typeof Device)[keyof typeof Device];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Device = {
  MOBILE: 'MOBILE',
  DESKTOP: 'DESKTOP',
  TABLET: 'TABLET',
} as const;

/**
 * Email address of the recipient of a payment link sent by email.
 */
export type BillingDetailsModelAnyOfEmail = string | null;

/**
 * Mobile phone number of the recipient of a payment link sent by SMS.
 * @pattern ^[+]?[0-9]+$
 */
export type BillingDetailsModelAnyOfMobilePhone = string | null;

/**
 * First name for the billing
 */
export type BillingDetailsModelAnyOfFirstName = string | null;

/**
 * Last name for the billing
 */
export type BillingDetailsModelAnyOfLastName = string | null;

/**
 * The first line of address for the billing
 */
export type BillingDetailsModelAnyOfAddress1 = string | null;

/**
 * The name of the city for the billing
 */
export type BillingDetailsModelAnyOfLocality = string | null;

/**
 * The postal code for the billing
 */
export type BillingDetailsModelAnyOfPostalCode = string | null;

/**
 * The name of the administrative area (e.g. state name) for the billing
 */
export type BillingDetailsModelAnyOfAdministrativeArea = string | null;

/**
 * Usually the ISO 2-letters code of the country, for the billing.
 */
export type BillingDetailsModelAnyOfCountryCode = string | null;

export type BillingDetailsModelAnyOf = {
  /** Email address of the recipient of a payment link sent by email. */
  email?: BillingDetailsModelAnyOfEmail;
  /**
   * Mobile phone number of the recipient of a payment link sent by SMS.
   * @pattern ^[+]?[0-9]+$
   */
  mobile_phone?: BillingDetailsModelAnyOfMobilePhone;
  /** First name for the billing */
  first_name?: BillingDetailsModelAnyOfFirstName;
  /** Last name for the billing */
  last_name?: BillingDetailsModelAnyOfLastName;
  /** The first line of address for the billing */
  address1?: BillingDetailsModelAnyOfAddress1;
  /** The name of the city for the billing */
  locality?: BillingDetailsModelAnyOfLocality;
  /** The postal code for the billing */
  postal_code?: BillingDetailsModelAnyOfPostalCode;
  /** The name of the administrative area (e.g. state name) for the billing */
  administrative_area?: BillingDetailsModelAnyOfAdministrativeArea;
  /** Usually the ISO 2-letters code of the country, for the billing. */
  country_code?: BillingDetailsModelAnyOfCountryCode;
};

export type BillingDetailsModel = BillingDetailsModelAnyOf | null;

/**
 * Map of values, browser information transmitted to PSP (PSD2)
 */
export interface BrowserInfo {
  [key: string]: unknown;
}

export interface PaymentRedirectRequestModel {
  device?: Device;
  billing_details?: BillingDetailsModel;
  /** B2B - Override the return url for the seller, for the case when the return url is on a website different than the website that performed the redirection. */
  callback_url_seller?: string;
  /** Payment call back url (usually for successful payment) */
  callback_url: string;
  /** Payment customer pending call back url */
  callback_pending_url?: string;
  /** Payment customer cancellation call back url */
  callback_cancel_url?: string;
  /** Payment denied call back url */
  callback_deny_url?: string;
  /** Payment error call back url */
  callback_exception_url?: string;
  /** Payer device IP address */
  emitter?: string;
  /** Name of the template to display */
  template_id?: string;
  /** Condition of payment selected by the customer */
  payment_condition_id?: string;
  /** Token when using PSP Direct POST method */
  token?: string;
  browser_info?: BrowserInfo;
  /** Id when PSP needs customer's identity a on dedicated platform */
  open_id?: string;
  /**
   * hash to verify a payment from a payment link
   * @pattern ^[0-9a-f]{64}$
   */
  payment_link_hash?: string;
  /**
   * <em>Optionnal</em> card cvc
   * @pattern ^[0-9]{3,4}$
   */
  card_cvc?: string;
  /** <em>Optionnal</em> name of the card holder as printed on the card */
  card_holder?: string;
}

export interface ProviderParametersModel {
  /** payment redirect url */
  url: string;
  /** payment redirect method */
  method: string;
  headers?: HeadersModel;
  /** payment redirect body */
  body?: string;
}

/**
 * provider response :ex query string added by the provider in redirect url after a payment
 */
export type PaymentOrderNotificationModelProviderResponse = string | null;

/**
 * update payment with provider response
 */
export interface PaymentOrderNotificationModel {
  /** provider response :ex query string added by the provider in redirect url after a payment */
  provider_response?: PaymentOrderNotificationModelProviderResponse;
}

/**
 * Payment status
 */
export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentStatus = {
  PENDING: 'PENDING',
  OK: 'OK',
  CANCELED: 'CANCELED',
  REFUSED_CM: 'REFUSED_CM',
  REFUSED_PSP: 'REFUSED_PSP',
} as const;

/**
 * payment status extracted from the provider notification
 */
export interface NotifyPaymentOrderNotificationStatus {
  /**
   * booking Id (file number)
   * @pattern ^\d+$
   */
  booking_id: string;
  payment_status: PaymentStatus;
  /** Payment amount */
  payment_amount: number;
  /**
   * The iso 3 currency. Ex: CNY,EUR,..
   * @minLength 3
   * @maxLength 3
   */
  payment_currency: string;
  /** id of the provider used to pay */
  provider_id: string;
  /** Codified value, looking like a bank card brand, required by accountant department. */
  payment_method?: string;
}

/**
 * Booking status.
 */
export type ValidPatchBookingRequestBookingStatusModel =
  (typeof ValidPatchBookingRequestBookingStatusModel)[keyof typeof ValidPatchBookingRequestBookingStatusModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ValidPatchBookingRequestBookingStatusModel = {
  VALIDATED: 'VALIDATED',
} as const;

/**
 * Transaction id
 */
export type PatchBookingPaymentModelTransactionId = string | null;

export interface PatchBookingPaymentModel {
  /** Transaction id */
  transaction_id?: PatchBookingPaymentModelTransactionId;
  /** Indicates the payment method, CB for payment by Bank Card, CH for payment by Cheque, WD for payment by wire transfer, SM for Sum Pay */
  method_id: string;
  /** Payment amount */
  amount: number;
  /**
   * for the deposit offset, directs to the account to be debited (max 60 charactères)
   * @maxLength 60
   */
  comments?: string;
}

export type PatchBookingPaymentsModel = PatchBookingPaymentModel[];

export interface PatchBookingRequestModel {
  booking_status?: ValidPatchBookingRequestBookingStatusModel;
  /** Customer id */
  customer_id?: string;
  payments?: PatchBookingPaymentsModel;
  /**
   * The iso 3 currency. Ex: CNY,EUR,..
   * @minLength 3
   * @maxLength 3
   */
  currency?: string;
}

/**
 * Language/Country, as returned by <code>GET&nbsp;/v0/locales</code> ; e.g. "en-US", "fr-FR", "ja-JP"
 */
export type AcceptLanguageParamModel =
  (typeof AcceptLanguageParamModel)[keyof typeof AcceptLanguageParamModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AcceptLanguageParamModel = {
  'fr-FR': 'fr-FR',
  'fr-BE': 'fr-BE',
  'nl-BE': 'nl-BE',
  'de-CH': 'de-CH',
  'fr-CH': 'fr-CH',
  'en-CH': 'en-CH',
  'nl-NL': 'nl-NL',
  'de-DE': 'de-DE',
  'en-IL': 'en-IL',
  'he-IL': 'he-IL',
  'it-IT': 'it-IT',
  'en-SE': 'en-SE',
  'pt-PT': 'pt-PT',
  'en-ZA': 'en-ZA',
  'es-ES': 'es-ES',
  'en-GB': 'en-GB',
  'en-CY': 'en-CY',
  'tr-TR': 'tr-TR',
  'ru-RU': 'ru-RU',
  'uk-UA': 'uk-UA',
  'en-DK': 'en-DK',
  'en-FI': 'en-FI',
  'en-NO': 'en-NO',
  'en-IE': 'en-IE',
  'en-US': 'en-US',
  'es-MX': 'es-MX',
  'fr-CA': 'fr-CA',
  'en-CA': 'en-CA',
  'es-PA': 'es-PA',
  'es-AR': 'es-AR',
  'es-CL': 'es-CL',
  'pt-BR': 'pt-BR',
  'es-CO': 'es-CO',
  'es-PE': 'es-PE',
  'es-VE': 'es-VE',
  'es-UY': 'es-UY',
  'en-CN': 'en-CN',
  'zh-CN': 'zh-CN',
  'zh-TW': 'zh-TW',
  'en-TW': 'en-TW',
  'en-HK': 'en-HK',
  'zh-HK': 'zh-HK',
  'en-AU': 'en-AU',
  'en-ID': 'en-ID',
  'id-ID': 'id-ID',
  'en-IN': 'en-IN',
  'ja-JP': 'ja-JP',
  'ko-KR': 'ko-KR',
  'en-MY': 'en-MY',
  'en-NZ': 'en-NZ',
  'en-SG': 'en-SG',
  'en-TH': 'en-TH',
  'vn-VN': 'vn-VN',
  'de-AT': 'de-AT',
  'ro-RO': 'ro-RO',
  'pl-PL': 'pl-PL',
  'et-EE': 'et-EE',
  'lv-LV': 'lv-LV',
  'en-LB': 'en-LB',
  'fr-MA': 'fr-MA',
  'se-SE': 'se-SE',
  'th-TH': 'th-TH',
  'en-JP': 'en-JP',
  'en-AF': 'en-AF',
  'en-AL': 'en-AL',
  'fr-DZ': 'fr-DZ',
  'fr-AD': 'fr-AD',
  'en-AO': 'en-AO',
  'en-AG': 'en-AG',
  'en-SA': 'en-SA',
  'en-AM': 'en-AM',
  'en-BS': 'en-BS',
  'en-BH': 'en-BH',
  'en-BD': 'en-BD',
  'en-BB': 'en-BB',
  'en-BZ': 'en-BZ',
  'en-BJ': 'en-BJ',
  'en-BM': 'en-BM',
  'en-BT': 'en-BT',
  'en-MM': 'en-MM',
  'es-BO': 'es-BO',
  'es-BW': 'es-BW',
  'en-BN': 'en-BN',
  'en-BG': 'en-BG',
  'en-BI': 'en-BI',
  'en-BF': 'en-BF',
  'en-CM': 'en-CM',
  'fr-CV': 'fr-CV',
  'en-KY': 'en-KY',
  'fr-CF': 'fr-CF',
  'en-SH': 'en-SH',
  'en-CO': 'en-CO',
  'en-KM': 'en-KM',
  'fr-CG': 'fr-CG',
  'en-KR': 'en-KR',
  'en-KP': 'en-KP',
  'en-CR': 'en-CR',
  'fr-CI': 'fr-CI',
  'en-CU': 'en-CU',
  'en-DJ': 'en-DJ',
  'en-DO': 'en-DO',
  'en-DM': 'en-DM',
  'en-EG': 'en-EG',
  'en-SV': 'en-SV',
  'en-AE': 'en-AE',
  'en-EC': 'en-EC',
  'fr-ET': 'fr-ET',
  'en-FJ': 'en-FJ',
  'en-GA': 'en-GA',
  'en-GM': 'en-GM',
  'en-GH': 'en-GH',
  'en-GI': 'en-GI',
  'gr-GR': 'gr-GR',
  'en-GD': 'en-GD',
  'en-GT': 'en-GT',
  'en-GN': 'en-GN',
  'fr-GW': 'fr-GW',
  'en-GQ': 'en-GQ',
  'en-GY': 'en-GY',
  'fr-GP': 'fr-GP',
  'fr-GF': 'fr-GF',
  'en-HT': 'en-HT',
  'en-HN': 'en-HN',
  'en-HU': 'en-HU',
  'fr-IQ': 'fr-IQ',
  'en-IR': 'en-IR',
  'en-IS': 'en-IS',
  'fr-TL': 'fr-TL',
  'en-JM': 'en-JM',
  'en-JO': 'en-JO',
  'en-KZ': 'en-KZ',
  'en-KH': 'en-KH',
  'en-KE': 'en-KE',
  'fr-KI': 'fr-KI',
  'en-KW': 'en-KW',
  'en-LA': 'en-LA',
  'fr-LS': 'fr-LS',
  'en-LR': 'en-LR',
  'en-LY': 'en-LY',
  'en-LI': 'en-LI',
  'fr-LU': 'fr-LU',
  'en-MO': 'en-MO',
  'en-MG': 'en-MG',
  'en-MW': 'en-MW',
  'en-MV': 'en-MV',
  'en-ML': 'en-ML',
  'en-MT': 'en-MT',
  'ma-MA': 'ma-MA',
  'en-MU': 'en-MU',
  'en-MR': 'en-MR',
  'en-YT': 'en-YT',
  'fr-MC': 'fr-MC',
  'en-MN': 'en-MN',
  'fr-MQ': 'fr-MQ',
  'en-MZ': 'en-MZ',
  'en-MD': 'en-MD',
  'fr-PS': 'fr-PS',
  'en-NA': 'en-NA',
  'fr-NR': 'fr-NR',
  'en-NP': 'en-NP',
  'en-NI': 'en-NI',
  'en-NE': 'en-NE',
  'en-NG': 'en-NG',
  'en-NC': 'en-NC',
  'fr-CK': 'fr-CK',
  'en-OM': 'en-OM',
  'en-UG': 'en-UG',
  'en-PK': 'en-PK',
  'en-PA': 'en-PA',
  'en-PG': 'en-PG',
  'es-PY': 'es-PY',
  'en-PH': 'en-PH',
  'fr-PN': 'fr-PN',
  'fr-PF': 'fr-PF',
  'en-PR': 'en-PR',
  'en-QA': 'en-QA',
  'en-RW': 'en-RW',
  'fr-RE': 'fr-RE',
  'fr-BL': 'fr-BL',
  'en-KN': 'en-KN',
  'en-MF': 'en-MF',
  'en-LC': 'en-LC',
  'en-SM': 'en-SM',
  'fr-PM': 'fr-PM',
  'fr-VC': 'fr-VC',
  'fr-SB': 'fr-SB',
  'en-WS': 'en-WS',
  'fr-ST': 'fr-ST',
  'en-SN': 'en-SN',
  'en-SC': 'en-SC',
  'fr-SL': 'fr-SL',
  'fr-SO': 'fr-SO',
  'fr-SD': 'fr-SD',
  'en-LK': 'en-LK',
  'en-SR': 'en-SR',
  'en-SZ': 'en-SZ',
  'en-SY': 'en-SY',
  'en-TZ': 'en-TZ',
  'en-TD': 'en-TD',
  'en-CZ': 'en-CZ',
  'fr-IO': 'fr-IO',
  'fr-TF': 'fr-TF',
  'en-TG': 'en-TG',
  'fr-TO': 'fr-TO',
  'en-TT': 'en-TT',
  'tu-TN': 'tu-TN',
  'en-TC': 'en-TC',
  'fr-TV': 'fr-TV',
  'fr-LB': 'fr-LB',
  'en-VU': 'en-VU',
  'fr-VA': 'fr-VA',
  'en-VG': 'en-VG',
  'en-VN': 'en-VN',
  'en-WF': 'en-WF',
  'en-YE': 'en-YE',
  'fr-YE': 'fr-YE',
  'en-RS': 'en-RS',
  'fr-CD': 'fr-CD',
  'fr-ZM': 'fr-ZM',
  'en-ZW': 'en-ZW',
  'fr-ME': 'fr-ME',
  'fr-FM': 'fr-FM',
  'fr-MH': 'fr-MH',
  'fr-PW': 'fr-PW',
  'en-HR': 'en-HR',
  'en-SI': 'en-SI',
  'en-SK': 'en-SK',
  'en-EE': 'en-EE',
  'en-LT': 'en-LT',
  'en-LV': 'en-LV',
  'en-MK': 'en-MK',
  'en-BA': 'en-BA',
  'en-UZ': 'en-UZ',
  'en-BY': 'en-BY',
  'fr-TJ': 'fr-TJ',
  'en-GE': 'en-GE',
  'en-AZ': 'en-AZ',
  'sk-SK': 'sk-SK',
  'fr-TM': 'fr-TM',
  'es-DO': 'es-DO',
  'fr-TN': 'fr-TN',
} as const;

/**
 * Optional Access Token (bearer)
 */
export type AuthorizationHeaderParamModel = string;

/**
 * Api_key provided by ClubMed API team
 */
export type ApiKeyHeaderParamModel = string;

/**
 * @pattern [A-Za-z0-9.[\]]+(>|>=|<=|<|==|!=).+
 */
export type FilterParamModel = string;

/**
 * string composed of a field name (can be a path), a comparison operator (>, >=, <=, <, ==, !=) and a value. Logical operator AND applies between filters
 */
export type FilterArrayParamModel = FilterParamModel[];

export type GetV0CountriesParams = {
  /**
   * string composed of a field name (can be a path), a comparison operator (>, >=, <=, <, ==, !=) and a value. Logical operator AND applies between filters
   */
  filter?: FilterArrayParamModel;
};

export type PostV3BookingsParams = {
  /**
   * Technical information provided, if needed, by Club Med to the partner
   */
  partner_type?: string;
};

/**
 * @summary Get list of available countries
 */
export const getV0Countries = (params?: GetV0CountriesParams) => {
  return fetcher<CountriesModel>({ url: `/v0/countries`, method: 'GET', params });
};

/**
 * @summary Returns the list of payment providers for this locale (<em>accept-language</em>).
 */
export const getV1PaymentProviders = () => {
  return fetcher<PaymentProviderListModel2>({ url: `/v1/payment_providers`, method: 'GET' });
};

/**
 * @summary Returns the proposal corresponding to the given proposal_id
 */
export const getV2ProposalsProposalId = (proposalId: string) => {
  return fetcher<ProposalResponseModelV1>({ url: `/v2/proposals/${proposalId}`, method: 'GET' });
};

/**
 * The response follow the model of an xmResponse with a finalisePaymentResponse.
 * @deprecated
 * @summary Retrieves the status of a payment
 */
export const getV0PaymentsPaymentIdStatus = (paymentId: string) => {
  return fetcher<PaymentStatusModel>({ url: `/v0/payments/${paymentId}/status`, method: 'GET' });
};

/**
 * @summary Payment schedule for a proposal
 */
export const getV1ProposalsProposalIdPaymentSchedule = (proposalId: string) => {
  return fetcher<ProposalPaymentScheduleModelV1>({
    url: `/v1/proposals/${proposalId}/payment_schedule`,
    method: 'GET',
  });
};

/**
 * This resource lists detailed information about a given account.
 * @summary Comprehensive information about a customer
 */
export const getV2CustomersCustomerIdProfile = (customerId: string) => {
  return fetcher<ProfileModelV2>({ url: `/v2/customers/${customerId}/profile`, method: 'GET' });
};

/**
 * @summary details of one booking
 */
export const getV3CustomersCustomerIdBookingsBookingId = (
  customerId: string,
  bookingId: string,
) => {
  return fetcher<CustomerBookingModelV3>({
    url: `/v3/customers/${customerId}/bookings/${bookingId}`,
    method: 'GET',
  });
};

/**
 * @summary payment schedules of one booking
 */
export const getV0CustomersCustomerIdBookingsBookingIdPaymentSchedules = (
  customerId: string,
  bookingId: string,
) => {
  return fetcher<CustomerBookingPaymentScheduleModel>({
    url: `/v0/customers/${customerId}/bookings/${bookingId}/payment_schedules`,
    method: 'GET',
  });
};

/**
 * @summary Retrieves the accommodations a cart contains for a given booking.
 */
export const getV0CustomersCustomerIdBookingsBookingIdCartAccommodations = (
  customerId: string,
  bookingId: string,
) => {
  return fetcher<CartUpgradeRoomModel>({
    url: `/v0/customers/${customerId}/bookings/${bookingId}/cart/accommodations`,
    method: 'GET',
  });
};

/**
 * @summary Get the payment schedule for a cart that contains a given booking.
 */
export const getV0CustomersCustomerIdBookingsBookingIdCartPaymentSchedule = (
  customerId: string,
  bookingId: string,
) => {
  return fetcher<PaymentScheduleModel>({
    url: `/v0/customers/${customerId}/bookings/${bookingId}/cart/payment_schedule`,
    method: 'GET',
  });
};

/**
 * @summary Post the status of a payment
 */
export const postV1Payments = (paymentOrderModel: PaymentOrderModel) => {
  return fetcher<PaymentIdModel>({
    url: `/v1/payments`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: paymentOrderModel,
  });
};

/**
 * Behind the scene, this endpoint acts like calling the POST /v3/proposals/search and the PUT /v1/proposals/{proposal_id}/attendees before creating the booking. To create a booking, the proposal must contain attendees information. The booking can be created with different statuses impacting the booking life cycle. The booking creation will decrease Club Med stock. The booking creation is required to create a payment. The accept-language must be the same as the one in the proposal creation.
 * @summary Creates a booking
 */
export const postV3Bookings = (
  createDirectBookingRequestModel: CreateDirectBookingRequestModel,
  params?: PostV3BookingsParams,
) => {
  return fetcher<CreateBookingResponseModel | CreateBookingResponseModel>({
    url: `/v3/bookings`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createDirectBookingRequestModel,
    params,
  });
};

/**
 * The only required parameters is the return url, to which the payment service provider will redirect to after
              the payment is processed. Other parameters are to be provided on case by case basis, for a given provider, payment methods,
              and use case flow.
              Some special case require a different processing of the descriptor than a redirection, like displaying an iFrame, or converting
              the descriptor into a QR-code.
        
 * @summary Get a description of an HTTP redirection to apply to go to the payment page.
 */
export const postV0PaymentsPaymentIdRedirectRequest = (
  paymentId: string,
  paymentRedirectRequestModel: PaymentRedirectRequestModel,
) => {
  return fetcher<ProviderParametersModel>({
    url: `/v0/payments/${paymentId}/redirect_request`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: paymentRedirectRequestModel,
  });
};

/**
 * @summary Update a payment order with notification from payment provider
 */
export const postV1PaymentsPaymentIdNotify = (
  paymentId: string,
  paymentOrderNotificationModel: PaymentOrderNotificationModel,
) => {
  return fetcher<NotifyPaymentOrderNotificationStatus>({
    url: `/v1/payments/${paymentId}/notify`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: paymentOrderNotificationModel,
  });
};

/**
 * @summary Allow to validate a booking by making one or more payments
 */
export const patchV2BookingsBookingId = (
  bookingId: string,
  patchBookingRequestModel: PatchBookingRequestModel,
) => {
  return fetcher<void>({
    url: `/v2/bookings/${bookingId}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: patchBookingRequestModel,
  });
};

export type GetV0CountriesResult = NonNullable<Awaited<ReturnType<typeof getV0Countries>>>;
export type GetV1PaymentProvidersResult = NonNullable<
  Awaited<ReturnType<typeof getV1PaymentProviders>>
>;
export type GetV2ProposalsProposalIdResult = NonNullable<
  Awaited<ReturnType<typeof getV2ProposalsProposalId>>
>;
export type GetV0PaymentsPaymentIdStatusResult = NonNullable<
  Awaited<ReturnType<typeof getV0PaymentsPaymentIdStatus>>
>;
export type GetV1ProposalsProposalIdPaymentScheduleResult = NonNullable<
  Awaited<ReturnType<typeof getV1ProposalsProposalIdPaymentSchedule>>
>;
export type GetV2CustomersCustomerIdProfileResult = NonNullable<
  Awaited<ReturnType<typeof getV2CustomersCustomerIdProfile>>
>;
export type GetV3CustomersCustomerIdBookingsBookingIdResult = NonNullable<
  Awaited<ReturnType<typeof getV3CustomersCustomerIdBookingsBookingId>>
>;
export type GetV0CustomersCustomerIdBookingsBookingIdPaymentSchedulesResult = NonNullable<
  Awaited<ReturnType<typeof getV0CustomersCustomerIdBookingsBookingIdPaymentSchedules>>
>;
export type GetV0CustomersCustomerIdBookingsBookingIdCartAccommodationsResult = NonNullable<
  Awaited<ReturnType<typeof getV0CustomersCustomerIdBookingsBookingIdCartAccommodations>>
>;
export type GetV0CustomersCustomerIdBookingsBookingIdCartPaymentScheduleResult = NonNullable<
  Awaited<ReturnType<typeof getV0CustomersCustomerIdBookingsBookingIdCartPaymentSchedule>>
>;
export type PostV1PaymentsResult = NonNullable<Awaited<ReturnType<typeof postV1Payments>>>;
export type PostV3BookingsResult = NonNullable<Awaited<ReturnType<typeof postV3Bookings>>>;
export type PostV0PaymentsPaymentIdRedirectRequestResult = NonNullable<
  Awaited<ReturnType<typeof postV0PaymentsPaymentIdRedirectRequest>>
>;
export type PostV1PaymentsPaymentIdNotifyResult = NonNullable<
  Awaited<ReturnType<typeof postV1PaymentsPaymentIdNotify>>
>;
export type PatchV2BookingsBookingIdResult = NonNullable<
  Awaited<ReturnType<typeof patchV2BookingsBookingId>>
>;
