/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * ClubMed API
 * Club Med, renowned for its luxury resort experiences, proudly introduces its dedicated API. This tool offers developers a gateway to the diverse services and information provided by Club Med, from vacation bookings to on-site activity details. By using this interface, partners and developers can effortlessly integrate Club Med's offerings into their platforms. Whether you're looking for destination details, making reservations, or discovering the latest promotions, the Club Med API ensures a streamlined user experience. Step into this digital realm and amplify your platforms with the Club Med API.
 * OpenAPI spec version: 0.3386.2
 */
import type {
  CartUpgradeRoomModel,
  CountriesModel,
  CreateBookingResponseModel,
  CreateDirectBookingRequestModel,
  CustomerBookingModelV3,
  CustomerBookingPaymentScheduleModel,
  GetV0CountriesParams,
  NotifyPaymentOrderNotificationStatus,
  PaymentIdModel,
  PaymentOrderModel,
  PaymentOrderNotificationModel,
  PaymentProviderListModel2,
  PaymentRedirectRequestModel,
  PaymentScheduleModel,
  PaymentStatusModel,
  PostV3BookingsParams,
  ProfileModelV2,
  ProposalPaymentScheduleModelV1,
  ProposalResponseModelV1,
  ProviderParametersModel,
} from './index.schemas';

import { fetcher } from '../../http/fetcher.js';

/**
 * @summary Get list of available countries
 */
export const getV0Countries = (params?: GetV0CountriesParams) => {
  return fetcher<CountriesModel>({ url: `/v0/countries`, method: 'GET', params });
};

/**
 * @summary Returns the list of payment providers for this locale (<em>accept-language</em>).
 */
export const getV1PaymentProviders = () => {
  return fetcher<PaymentProviderListModel2>({ url: `/v1/payment_providers`, method: 'GET' });
};

/**
 * @summary Returns the proposal corresponding to the given proposal_id
 */
export const getV2ProposalsProposalId = (proposalId: string) => {
  return fetcher<ProposalResponseModelV1>({ url: `/v2/proposals/${proposalId}`, method: 'GET' });
};

/**
 * The response follow the model of an xmResponse with a finalisePaymentResponse.
 * @summary Retrieves the status of a payment
 */
export const getV0PaymentsPaymentIdStatus = (paymentId: string) => {
  return fetcher<PaymentStatusModel>({ url: `/v0/payments/${paymentId}/status`, method: 'GET' });
};

/**
 * @summary Payment schedule for a proposal
 */
export const getV1ProposalsProposalIdPaymentSchedule = (proposalId: string) => {
  return fetcher<ProposalPaymentScheduleModelV1>({
    url: `/v1/proposals/${proposalId}/payment_schedule`,
    method: 'GET',
  });
};

/**
 * This resource lists detailed information about a given account.
 * @summary Comprehensive information about a customer
 */
export const getV2CustomersCustomerIdProfile = (customerId: string) => {
  return fetcher<ProfileModelV2>({ url: `/v2/customers/${customerId}/profile`, method: 'GET' });
};

/**
 * @summary details of one booking
 */
export const getV3CustomersCustomerIdBookingsBookingId = (
  customerId: string,
  bookingId: string,
) => {
  return fetcher<CustomerBookingModelV3>({
    url: `/v3/customers/${customerId}/bookings/${bookingId}`,
    method: 'GET',
  });
};

/**
 * @summary payment schedules of one booking
 */
export const getV0CustomersCustomerIdBookingsBookingIdPaymentSchedules = (
  customerId: string,
  bookingId: string,
) => {
  return fetcher<CustomerBookingPaymentScheduleModel>({
    url: `/v0/customers/${customerId}/bookings/${bookingId}/payment_schedules`,
    method: 'GET',
  });
};

/**
 * @summary Retrieves the accommodations a cart contains for a given booking.
 */
export const getV0CustomersCustomerIdBookingsBookingIdCartAccommodations = (
  customerId: string,
  bookingId: string,
) => {
  return fetcher<CartUpgradeRoomModel>({
    url: `/v0/customers/${customerId}/bookings/${bookingId}/cart/accommodations`,
    method: 'GET',
  });
};

/**
 * @summary Get the payment schedule for a cart that contains a given booking.
 */
export const getV0CustomersCustomerIdBookingsBookingIdCartPaymentSchedule = (
  customerId: string,
  bookingId: string,
) => {
  return fetcher<PaymentScheduleModel>({
    url: `/v0/customers/${customerId}/bookings/${bookingId}/cart/payment_schedule`,
    method: 'GET',
  });
};

/**
 * @summary Post the status of a payment
 */
export const postV1Payments = (paymentOrderModel: PaymentOrderModel) => {
  return fetcher<PaymentIdModel>({
    url: `/v1/payments`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: paymentOrderModel,
  });
};

/**
 * Behind the scene, this endpoint acts like calling the POST /v3/proposals/search and the PUT /v1/proposals/{proposal_id}/attendees before creating the booking. To create a booking, the proposal must contain attendees information. The booking can be created with different statuses impacting the booking life cycle. The booking creation will decrease Club Med stock. The booking creation is required to create a payment. The accept-language must be the same as the one in the proposal creation.
 * @summary Creates a booking
 */
export const postV3Bookings = (
  createDirectBookingRequestModel: CreateDirectBookingRequestModel,
  params?: PostV3BookingsParams,
) => {
  return fetcher<CreateBookingResponseModel | CreateBookingResponseModel>({
    url: `/v3/bookings`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createDirectBookingRequestModel,
    params,
  });
};

/**
 * The only required parameters is the return url, to which the payment service provider will redirect to after
              the payment is processed. Other parameters are to be provided on case by case basis, for a given provider, payment methods,
              and use case flow.
              Some special case require a different processing of the descriptor than a redirection, like displaying an iFrame, or converting
              the descriptor into a QR-code.
        
 * @summary Get a description of an HTTP redirection to apply to go to the payment page.
 */
export const postV0PaymentsPaymentIdRedirectRequest = (
  paymentId: string,
  paymentRedirectRequestModel: PaymentRedirectRequestModel,
) => {
  return fetcher<ProviderParametersModel>({
    url: `/v0/payments/${paymentId}/redirect_request`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: paymentRedirectRequestModel,
  });
};

/**
 * @summary Update a payment order with notification from payment provider
 */
export const postV1PaymentsPaymentIdNotify = (
  paymentId: string,
  paymentOrderNotificationModel: PaymentOrderNotificationModel,
) => {
  return fetcher<NotifyPaymentOrderNotificationStatus>({
    url: `/v1/payments/${paymentId}/notify`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: paymentOrderNotificationModel,
  });
};

export type GetV0CountriesResult = NonNullable<Awaited<ReturnType<typeof getV0Countries>>>;
export type GetV1PaymentProvidersResult = NonNullable<
  Awaited<ReturnType<typeof getV1PaymentProviders>>
>;
export type GetV2ProposalsProposalIdResult = NonNullable<
  Awaited<ReturnType<typeof getV2ProposalsProposalId>>
>;
export type GetV0PaymentsPaymentIdStatusResult = NonNullable<
  Awaited<ReturnType<typeof getV0PaymentsPaymentIdStatus>>
>;
export type GetV1ProposalsProposalIdPaymentScheduleResult = NonNullable<
  Awaited<ReturnType<typeof getV1ProposalsProposalIdPaymentSchedule>>
>;
export type GetV2CustomersCustomerIdProfileResult = NonNullable<
  Awaited<ReturnType<typeof getV2CustomersCustomerIdProfile>>
>;
export type GetV3CustomersCustomerIdBookingsBookingIdResult = NonNullable<
  Awaited<ReturnType<typeof getV3CustomersCustomerIdBookingsBookingId>>
>;
export type GetV0CustomersCustomerIdBookingsBookingIdPaymentSchedulesResult = NonNullable<
  Awaited<ReturnType<typeof getV0CustomersCustomerIdBookingsBookingIdPaymentSchedules>>
>;
export type GetV0CustomersCustomerIdBookingsBookingIdCartAccommodationsResult = NonNullable<
  Awaited<ReturnType<typeof getV0CustomersCustomerIdBookingsBookingIdCartAccommodations>>
>;
export type GetV0CustomersCustomerIdBookingsBookingIdCartPaymentScheduleResult = NonNullable<
  Awaited<ReturnType<typeof getV0CustomersCustomerIdBookingsBookingIdCartPaymentSchedule>>
>;
export type PostV1PaymentsResult = NonNullable<Awaited<ReturnType<typeof postV1Payments>>>;
export type PostV3BookingsResult = NonNullable<Awaited<ReturnType<typeof postV3Bookings>>>;
export type PostV0PaymentsPaymentIdRedirectRequestResult = NonNullable<
  Awaited<ReturnType<typeof postV0PaymentsPaymentIdRedirectRequest>>
>;
export type PostV1PaymentsPaymentIdNotifyResult = NonNullable<
  Awaited<ReturnType<typeof postV1PaymentsPaymentIdNotify>>
>;
