export enum PspProviders {
  EIXOPAY = 'EIXOPAY',
  HIPAY = 'MHIPAY',
  HIPAY_PAYPAL = 'MHIPAYPP',
  EVOXPAY = 'EVOXPAY',
  EGLOBALCOLLECT = 'EGLOBALCOLLECT',
  ENETPAY = 'ENETPAY',
  EPAYGATE = 'EPAYGATE',
  MCYBERSOURCE = 'MCYBERSOURCE',
  MUPLIFT = 'MUPLIFT',
  EHIPAYBNPL = 'EHIPAYBNPL',
  M99BILLW = 'M99BILLW',
}
